//! Jinja2-style chat template engine for GGUF models.
//!
//! GGUF files store a `tokenizer.chat_template` metadata field containing a
//! Jinja2-format template string. This module implements enough of Jinja2 to
//! handle the common patterns used by popular model families:
//! ChatML, Llama, Mistral, Qwen, Gemma, Phi, TinyLlama, etc.

use crate::types::ChatMessage;

mod eval;
mod fallbacks;
mod parser;

pub use fallbacks::chatml_fallback;

use eval::{eval_block, EvalCtx, EvalState};
use fallbacks::{gemma_fallback, vicuna_fallback};
use parser::tokenize;

/// Apply a Jinja2-style chat template to a list of messages.
///
/// Returns `None` if the template cannot be parsed, so callers can fall back to ChatML.
pub fn apply_chat_template(
    template: &str,
    messages: &[ChatMessage],
    bos_token: &str,
    eos_token: &str,
    add_generation_prompt: bool,
) -> Option<String> {
    let tokens = tokenize(template)?;
    let mut output = String::new();
    let ctx = EvalCtx {
        tokens: &tokens,
        messages,
        bos_token,
        eos_token,
        add_generation_prompt,
    };
    let mut state = EvalState::new(messages);
    eval_block(&ctx, 0, &mut output, &mut state)?;
    Some(output)
}

/// Extract stop strings from a chat template.
///
/// These are role markers that, when generated by the model, indicate the start
/// of a new turn and should terminate generation. Common patterns:
/// - Zephyr/TinyLlama: `<|user|>`, `<|system|>`
/// - ChatML: `<|im_end|>`
/// - Llama: `[INST]`
pub fn extract_stop_strings(template: Option<&str>) -> Vec<String> {
    let tmpl = match template {
        Some(t) => t,
        None => return vec!["<|im_end|>".to_string()], // ChatML fallback
    };

    let mut stops = Vec::new();

    // Scan template for known role marker patterns
    for marker in &[
        "<|user|>",
        "<|system|>",
        "<|im_end|>",
        "<|im_start|>",
        "[INST]",
        "<|eot_id|>",
    ] {
        if tmpl.contains(marker) {
            stops.push(marker.to_string());
        }
    }

    // For Zephyr-style templates, `<|assistant|>` in the middle of generation
    // means the model is hallucinating a new assistant turn after ending its own.
    if tmpl.contains("<|assistant|>") && tmpl.contains("<|user|>") {
        // Already have <|user|>, also stop on <|assistant|> if model re-emits it
        if !stops.contains(&"<|assistant|>".to_string()) {
            stops.push("<|assistant|>".to_string());
        }
    }

    stops
}

/// Build a chat prompt using the given template, falling back to ChatML.
///
/// This is the main entry point for chat prompt construction.
pub fn build_prompt(
    messages: &[ChatMessage],
    template: Option<&str>,
    bos_token: &str,
    eos_token: &str,
) -> String {
    build_prompt_with_model(messages, template, bos_token, eos_token, None)
}

/// Build prompt with optional model name hint for fallback template selection.
pub fn build_prompt_with_model(
    messages: &[ChatMessage],
    template: Option<&str>,
    bos_token: &str,
    eos_token: &str,
    model_name: Option<&str>,
) -> String {
    if let Some(tmpl) = template {
        if let Some(result) = apply_chat_template(tmpl, messages, bos_token, eos_token, true) {
            tracing::debug!(template_matched = true, "DIAG: chat template applied");
            return result;
        }
        // Template failed — try architecture-specific fallbacks before ChatML
        if tmpl.contains("start_of_turn") {
            tracing::warn!(
                fallback = "gemma",
                "DIAG: chat template failed, using gemma fallback"
            );
            return gemma_fallback(messages);
        }
        tracing::warn!(
            fallback = "chatml",
            "DIAG: chat template failed, using fallback"
        );
    } else {
        // No template: pick fallback based on model name heuristic
        if let Some(name) = model_name {
            let name_lower = name.to_lowercase();
            if name_lower.contains("llava") || name_lower.contains("vicuna") {
                tracing::debug!(
                    model_name = name,
                    fallback = "vicuna",
                    "DIAG: no chat template, using vicuna fallback"
                );
                return vicuna_fallback(messages);
            }
            if name_lower.contains("gemma") {
                tracing::debug!(
                    model_name = name,
                    fallback = "gemma",
                    "DIAG: no chat template, using gemma fallback"
                );
                return gemma_fallback(messages);
            }
        }
        tracing::debug!(
            template_matched = false,
            fallback = "chatml",
            "DIAG: no chat template, using fallback"
        );
    }
    chatml_fallback(messages)
}

#[cfg(test)]
mod tests;
