//! Jinja2-style chat template engine for GGUF models.
//!
//! GGUF files store a `tokenizer.chat_template` metadata field containing a
//! Jinja2-format template string. This module implements enough of Jinja2 to
//! handle the common patterns used by popular model families:
//! ChatML, Llama, Mistral, Qwen, Gemma, Phi, TinyLlama, etc.

use crate::types::{ChatMessage, Role};

mod eval;
mod fallbacks;
mod parser;

pub use fallbacks::chatml_fallback;

use eval::{eval_block, EvalCtx, EvalState};
use fallbacks::{
    gemma_fallback, llama3_fallback, mistral_fallback, vicuna_fallback, zephyr_fallback,
};
use parser::tokenize;

/// Apply a Jinja2-style chat template to a list of messages.
///
/// Returns `None` if the template could not be applied, so callers can fall
/// back to ChatML.
///
/// That includes a template which parses and evaluates but renders *nothing*
/// from a non-empty message list. Only structural token errors (an unclosed
/// `{% for %}`, a bare `{{`) actually fail evaluation here; an unknown filter,
/// an unknown variable, a stray `{% endfor %}` and an unclosed `{% if %}` all
/// evaluate quietly to the empty string. Reporting those as success handed the
/// model an empty prompt — no system message, no user turn, and for a VLM no
/// `<image>` placeholder, so vision embeddings were prepended instead of being
/// inserted at the right token position.
pub fn apply_chat_template(
    template: &str,
    messages: &[ChatMessage],
    bos_token: &str,
    eos_token: &str,
    add_generation_prompt: bool,
) -> Option<String> {
    let tokens = tokenize(template)?;
    let mut output = String::new();
    let ctx = EvalCtx {
        tokens: &tokens,
        messages,
        bos_token,
        eos_token,
        add_generation_prompt,
        depth: std::cell::Cell::new(0),
    };
    let mut state = EvalState::new(messages);
    eval_block(&ctx, 0, &mut output, &mut state)?;
    if !messages.is_empty() && output.trim().is_empty() {
        return None;
    }
    Some(output)
}

/// Extract stop strings from a chat template.
///
/// These are role markers that, when generated by the model, indicate the start
/// of a new turn and should terminate generation. Common patterns:
/// - Zephyr/TinyLlama: `<|user|>`, `<|system|>`
/// - ChatML: `<|im_end|>`
/// - Llama: `[INST]`
pub fn extract_stop_strings(template: Option<&str>) -> Vec<String> {
    let tmpl = match template {
        Some(t) => t,
        None => return vec!["<|im_end|>".to_string()], // ChatML fallback
    };

    let mut stops = Vec::new();

    // Special tokens that are NEVER legitimate assistant output, regardless of
    // what this model's template contains. A GGUF whose chat template says one
    // family but whose weights were tuned on another will emit the other
    // family's markers — reported live 2026-07-25: a Llama-3.2 q8_0 returned
    // `<|im_end|>hello\n</im_start>` even though its template is not ChatML, so
    // scanning the template alone could never catch it.
    //
    // Only the `<|...|>` / `<...>` special-token forms are listed. `[INST]` and
    // `</s>` stay template-gated below because they can plausibly appear in real
    // prose (code, XML), whereas these cannot.
    for marker in &[
        "<|im_end|>",
        "<|im_start|>",
        "<|eot_id|>",
        "<|eom_id|>",
        "<|start_header_id|>",
        "<|endoftext|>",
        "<end_of_turn>",
    ] {
        stops.push(marker.to_string());
    }

    // Scan the template for turn-boundary markers. Anything present here is a
    // marker this model's own template uses, so seeing it mid-generation means
    // the model has ended its turn (or started hallucinating another one) and we
    // should stop rather than pass the marker through as visible text.
    //
    // This list must cover what models actually EMIT, which is not always the
    // token the tokenizer declares as EOS. Observed live 2026-07-25: a
    // Llama-3.2 model emitted `<|eom_id|><|start_header_id|>assistant<|end_header_id|>`
    // into user-visible content because only `<|eot_id|>` was listed —
    // Llama 3.1+ uses `<|eom_id|>` ("end of message") when it believes it is
    // making a tool call, and neither the header markers nor `<|eom_id|>` were
    // being caught.
    for marker in &[
        // ChatML (Qwen, Hermes, many finetunes)
        "<|im_end|>",
        "<|im_start|>",
        // Zephyr / TinyLlama style
        "<|user|>",
        "<|system|>",
        // Llama 2 / Mistral
        "[INST]",
        "</s>",
        // Llama 3.x — `eot` ends a turn, `eom` ends a message (tool calls), and
        // a header marker mid-stream is the model opening a turn it shouldn't.
        "<|eot_id|>",
        "<|eom_id|>",
        "<|start_header_id|>",
        // Gemma
        "<end_of_turn>",
        // GPT-2 style vocabularies (Qwen base, several small models)
        "<|endoftext|>",
    ] {
        if tmpl.contains(marker) && !stops.iter().any(|s| s == marker) {
            stops.push(marker.to_string());
        }
    }

    // For Zephyr-style templates, `<|assistant|>` in the middle of generation
    // means the model is hallucinating a new assistant turn after ending its own.
    if tmpl.contains("<|assistant|>") && tmpl.contains("<|user|>") {
        // Already have <|user|>, also stop on <|assistant|> if model re-emits it
        if !stops.contains(&"<|assistant|>".to_string()) {
            stops.push("<|assistant|>".to_string());
        }
    }

    stops
}

/// Build a chat prompt using the given template, falling back to ChatML.
///
/// This is the main entry point for chat prompt construction.
///
/// `model_name` is REQUIRED, not optional, and passing `None` is a real choice
/// with a real cost: it is the only thing that lets a failed template degrade
/// to the right family format instead of ChatML. This used to be a
/// four-argument convenience wrapper that hardcoded `None`, and six of the
/// seven production call sites used it — so the gemma / LLaVA fallbacks could
/// never fire on the OpenAI, Anthropic, streaming, or router paths, and a
/// Llama-3 model whose template failed was asked to speak ChatML (which is
/// where the stray `<|im_end|>` markers came from). Pass the model id unless
/// you genuinely do not have one.
pub fn build_prompt(
    messages: &[ChatMessage],
    template: Option<&str>,
    bos_token: &str,
    eos_token: &str,
    model_name: Option<&str>,
) -> String {
    build_prompt_with_model(messages, template, bos_token, eos_token, model_name)
}

/// Pick a fallback prompt format from the model name alone.
///
/// Returns the rendered prompt plus the name of the format chosen, or `None`
/// when the name carries no usable signal and the caller should use ChatML.
/// Shared by both `build_prompt_with_model` branches: a model with no template
/// at all and a model whose template failed to evaluate want the same answer.
/// Reaching ChatML for a model that is not a ChatML model is the failure mode
/// that produced stray `<|im_end|>` markers in Llama-3 replies for several
/// releases: the model answers in whatever format it was asked in. Every family
/// we can recognise by name gets its own format here, so a template we cannot
/// evaluate degrades to the right shape instead of a foreign one.
///
/// Checked before the generic families because a name can match more than one
/// substring — `llava-v1.6-mistral-7b` is a LLaVA model that must use the
/// vicuna/LLaVA prompt, not Mistral's.
fn fallback_by_model_name(
    messages: &[ChatMessage],
    model_name: Option<&str>,
) -> Option<(String, &'static str)> {
    let name_lower = model_name?.to_lowercase();
    if name_lower.contains("llava") || name_lower.contains("vicuna") {
        return Some((vicuna_fallback(messages), "vicuna"));
    }
    // Checked before the llama families: "tinyllama" contains "llama" and this
    // is a Zephyr-format model, not a Llama-chat one.
    if name_lower.contains("tinyllama") || name_lower.contains("zephyr") {
        return Some((zephyr_fallback(messages), "zephyr"));
    }
    if name_lower.contains("gemma") {
        return Some((gemma_fallback(messages), "gemma"));
    }
    if name_lower.contains("llama-3")
        || name_lower.contains("llama3")
        || name_lower.contains("llama_3")
    {
        return Some((llama3_fallback(messages), "llama3"));
    }
    // `mixtral` and `ministral`/`magistral` share the [INST] convention.
    if name_lower.contains("mistral")
        || name_lower.contains("mixtral")
        || name_lower.contains("ministral")
        || name_lower.contains("magistral")
    {
        return Some((mistral_fallback(messages), "mistral"));
    }
    None
}

/// System message supplied when the caller sends none and the model's template
/// shows it expects one.
pub const DEFAULT_SYSTEM_PROMPT: &str = "You are a helpful assistant.";

/// Whether this template has a system-role branch it will actually honour.
///
/// Two families must be told apart:
///
/// - Zephyr/TinyLlama, Phi and Llama-3 branch on `role == 'system'` and emit a
///   distinct marker for it. These models are trained with a system turn and
///   behave badly without one.
/// - Gemma and Mistral do NOT support a system role and say so with
///   `raise_exception`. Our evaluator deliberately treats `raise_exception` as
///   a silent skip, so injecting a system message for them does not fail
///   loudly — it renders a turn the model was never trained on (Gemma would
///   emit `<start_of_turn>system`). The presence of `raise_exception` is
///   therefore a hard veto.
///
/// Absent positive evidence, this returns false: not injecting is always safe,
/// injecting into the wrong template is not.
fn template_expects_system(template: &str) -> bool {
    if template.contains("raise_exception") {
        return false;
    }
    template.contains("'system'") || template.contains("\"system\"")
}

/// Ensure a usable system turn, returning an owned list only when one is needed.
///
/// A blank system message is treated as absent — it renders an empty system
/// turn, which for TinyLlama reproduces the exact failure this guards against
/// (verified: an empty system message still yields a blank reply).
fn with_system_message(messages: &[ChatMessage]) -> Option<Vec<ChatMessage>> {
    if messages.is_empty() {
        return None;
    }
    match messages.iter().position(|m| matches!(m.role, Role::System)) {
        // Caller supplied a real system message — never override it.
        Some(i) if !messages[i].content.trim().is_empty() => None,
        Some(i) => {
            let mut v = messages.to_vec();
            v[i].content = DEFAULT_SYSTEM_PROMPT.to_string();
            Some(v)
        }
        None => {
            let mut v = Vec::with_capacity(messages.len() + 1);
            v.push(ChatMessage {
                role: Role::System,
                content: DEFAULT_SYSTEM_PROMPT.to_string(),
                images: Vec::new(),
            });
            v.extend_from_slice(messages);
            Some(v)
        }
    }
}

/// Build prompt with optional model name hint for fallback template selection.
///
/// When the model's template shows it expects a system turn and the caller sent
/// none, a neutral default is supplied. TinyLlama-1.1B-Chat answers a bare user
/// question with nothing but a `<|user|>` turn marker — stop-truncation strips
/// it and the user sees a blank reply reported as a successful completion. The
/// same question with a system message is answered normally.
pub fn build_prompt_with_model(
    messages: &[ChatMessage],
    template: Option<&str>,
    bos_token: &str,
    eos_token: &str,
    model_name: Option<&str>,
) -> String {
    let injected = template
        .filter(|t| template_expects_system(t))
        .and_then(|_| with_system_message(messages));
    let messages: &[ChatMessage] = injected.as_deref().unwrap_or(messages);

    if let Some(tmpl) = template {
        if let Some(result) = apply_chat_template(tmpl, messages, bos_token, eos_token, true) {
            tracing::debug!(template_matched = true, "DIAG: chat template applied");
            return result;
        }
        // Template failed. Prefer evidence from the template body itself — it
        // describes the model that shipped it — then fall back to the same
        // model-name heuristic the no-template branch uses. Reaching ChatML
        // here would drop LLaVA's `<image>` placeholder, which prepends the
        // vision embeddings instead of inserting them at the right position.
        if tmpl.contains("start_of_turn") {
            tracing::warn!(
                fallback = "gemma",
                "DIAG: chat template failed, using gemma fallback"
            );
            return gemma_fallback(messages);
        }
        if let Some((prompt, fallback)) = fallback_by_model_name(messages, model_name) {
            tracing::warn!(
                model_name = model_name,
                fallback,
                "DIAG: chat template failed, using model-name fallback"
            );
            return prompt;
        }
        tracing::warn!(
            fallback = "chatml",
            "DIAG: chat template failed, using fallback"
        );
    } else {
        // No template: pick fallback based on model name heuristic
        if let Some((prompt, fallback)) = fallback_by_model_name(messages, model_name) {
            tracing::debug!(
                model_name = model_name,
                fallback,
                "DIAG: no chat template, using model-name fallback"
            );
            return prompt;
        }
        tracing::debug!(
            template_matched = false,
            fallback = "chatml",
            "DIAG: no chat template, using fallback"
        );
    }
    chatml_fallback(messages)
}

#[cfg(test)]
mod tests;
