//! Jinja2-style chat template engine for GGUF models.
//!
//! GGUF files store a `tokenizer.chat_template` metadata field containing a
//! Jinja2-format template string. This module implements enough of Jinja2 to
//! handle the common patterns used by popular model families:
//! ChatML, Llama, Mistral, Qwen, Gemma, Phi, TinyLlama, etc.

use crate::types::ChatMessage;

mod eval;
mod fallbacks;
mod parser;

pub use fallbacks::chatml_fallback;

use eval::{eval_block, EvalCtx, EvalState};
use fallbacks::{gemma_fallback, vicuna_fallback};
use parser::tokenize;

/// Apply a Jinja2-style chat template to a list of messages.
///
/// Returns `None` if the template could not be applied, so callers can fall
/// back to ChatML.
///
/// That includes a template which parses and evaluates but renders *nothing*
/// from a non-empty message list. Only structural token errors (an unclosed
/// `{% for %}`, a bare `{{`) actually fail evaluation here; an unknown filter,
/// an unknown variable, a stray `{% endfor %}` and an unclosed `{% if %}` all
/// evaluate quietly to the empty string. Reporting those as success handed the
/// model an empty prompt — no system message, no user turn, and for a VLM no
/// `<image>` placeholder, so vision embeddings were prepended instead of being
/// inserted at the right token position.
pub fn apply_chat_template(
    template: &str,
    messages: &[ChatMessage],
    bos_token: &str,
    eos_token: &str,
    add_generation_prompt: bool,
) -> Option<String> {
    let tokens = tokenize(template)?;
    let mut output = String::new();
    let ctx = EvalCtx {
        tokens: &tokens,
        messages,
        bos_token,
        eos_token,
        add_generation_prompt,
        depth: std::cell::Cell::new(0),
    };
    let mut state = EvalState::new(messages);
    eval_block(&ctx, 0, &mut output, &mut state)?;
    if !messages.is_empty() && output.trim().is_empty() {
        return None;
    }
    Some(output)
}

/// Extract stop strings from a chat template.
///
/// These are role markers that, when generated by the model, indicate the start
/// of a new turn and should terminate generation. Common patterns:
/// - Zephyr/TinyLlama: `<|user|>`, `<|system|>`
/// - ChatML: `<|im_end|>`
/// - Llama: `[INST]`
pub fn extract_stop_strings(template: Option<&str>) -> Vec<String> {
    let tmpl = match template {
        Some(t) => t,
        None => return vec!["<|im_end|>".to_string()], // ChatML fallback
    };

    let mut stops = Vec::new();

    // Scan template for known role marker patterns
    for marker in &[
        "<|user|>",
        "<|system|>",
        "<|im_end|>",
        "<|im_start|>",
        "[INST]",
        "<|eot_id|>",
    ] {
        if tmpl.contains(marker) {
            stops.push(marker.to_string());
        }
    }

    // For Zephyr-style templates, `<|assistant|>` in the middle of generation
    // means the model is hallucinating a new assistant turn after ending its own.
    if tmpl.contains("<|assistant|>") && tmpl.contains("<|user|>") {
        // Already have <|user|>, also stop on <|assistant|> if model re-emits it
        if !stops.contains(&"<|assistant|>".to_string()) {
            stops.push("<|assistant|>".to_string());
        }
    }

    stops
}

/// Build a chat prompt using the given template, falling back to ChatML.
///
/// This is the main entry point for chat prompt construction.
pub fn build_prompt(
    messages: &[ChatMessage],
    template: Option<&str>,
    bos_token: &str,
    eos_token: &str,
) -> String {
    build_prompt_with_model(messages, template, bos_token, eos_token, None)
}

/// Pick a fallback prompt format from the model name alone.
///
/// Returns the rendered prompt plus the name of the format chosen, or `None`
/// when the name carries no usable signal and the caller should use ChatML.
/// Shared by both `build_prompt_with_model` branches: a model with no template
/// at all and a model whose template failed to evaluate want the same answer.
fn fallback_by_model_name(
    messages: &[ChatMessage],
    model_name: Option<&str>,
) -> Option<(String, &'static str)> {
    let name_lower = model_name?.to_lowercase();
    if name_lower.contains("llava") || name_lower.contains("vicuna") {
        return Some((vicuna_fallback(messages), "vicuna"));
    }
    if name_lower.contains("gemma") {
        return Some((gemma_fallback(messages), "gemma"));
    }
    None
}

/// Build prompt with optional model name hint for fallback template selection.
pub fn build_prompt_with_model(
    messages: &[ChatMessage],
    template: Option<&str>,
    bos_token: &str,
    eos_token: &str,
    model_name: Option<&str>,
) -> String {
    if let Some(tmpl) = template {
        if let Some(result) = apply_chat_template(tmpl, messages, bos_token, eos_token, true) {
            tracing::debug!(template_matched = true, "DIAG: chat template applied");
            return result;
        }
        // Template failed. Prefer evidence from the template body itself — it
        // describes the model that shipped it — then fall back to the same
        // model-name heuristic the no-template branch uses. Reaching ChatML
        // here would drop LLaVA's `<image>` placeholder, which prepends the
        // vision embeddings instead of inserting them at the right position.
        if tmpl.contains("start_of_turn") {
            tracing::warn!(
                fallback = "gemma",
                "DIAG: chat template failed, using gemma fallback"
            );
            return gemma_fallback(messages);
        }
        if let Some((prompt, fallback)) = fallback_by_model_name(messages, model_name) {
            tracing::warn!(
                model_name = model_name,
                fallback,
                "DIAG: chat template failed, using model-name fallback"
            );
            return prompt;
        }
        tracing::warn!(
            fallback = "chatml",
            "DIAG: chat template failed, using fallback"
        );
    } else {
        // No template: pick fallback based on model name heuristic
        if let Some((prompt, fallback)) = fallback_by_model_name(messages, model_name) {
            tracing::debug!(
                model_name = model_name,
                fallback,
                "DIAG: no chat template, using model-name fallback"
            );
            return prompt;
        }
        tracing::debug!(
            template_matched = false,
            fallback = "chatml",
            "DIAG: no chat template, using fallback"
        );
    }
    chatml_fallback(messages)
}

#[cfg(test)]
mod tests;
