use serde::{Deserialize, Serialize};

use crate::types::{ChatMessage, ImageData, SamplingParams};

use super::DEFAULT_TOP_K;

// ---- Request types ----

#[derive(Debug, Serialize, Deserialize)]
pub struct ChatCompletionRequest {
    pub model: String,
    pub messages: Vec<ApiChatMessage>,
    #[serde(default = "default_temperature")]
    pub temperature: f32,
    #[serde(default = "default_top_p")]
    pub top_p: f32,
    /// Upper bound on generated tokens. Accept either `max_tokens` (legacy)
    /// or `max_completion_tokens` (the spelling current OpenAI SDKs default to
    /// for o-series / gpt-5 reasoning models). Without this alias, a caller
    /// targeting a reasoning model through our proxy silently gets the 2048
    /// default, and reasoning tokens eat the whole budget before any content
    /// is emitted.
    #[serde(default = "default_max_tokens", alias = "max_completion_tokens")]
    pub max_tokens: u32,
    #[serde(default)]
    pub stream: bool,
    #[serde(default)]
    pub stop: Option<StopSequence>,
    #[serde(default)]
    pub frequency_penalty: f32,
    #[serde(default)]
    pub presence_penalty: f32,
    /// Tool definitions for function calling (OpenAI-compatible).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tools: Option<Vec<ToolDefinition>>,
    /// Controls which tool the model calls: "none", "auto", or {"type":"function","function":{"name":"..."}}.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tool_choice: Option<serde_json::Value>,
    /// Whether to return log probabilities for output tokens.
    #[serde(default)]
    pub logprobs: bool,
    /// Number of top log probabilities to return per token (0-20). Requires logprobs=true.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub top_logprobs: Option<u32>,
    /// Structured output format. Supports:
    /// - `{"type": "json_object"}` — model outputs valid JSON
    /// - `{"type": "json_schema", "json_schema": {"name": "...", "schema": {...}}}` — constrained to schema
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub response_format: Option<ResponseFormat>,
    /// Optional session ID for multi-turn KV-cache reuse.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub session_id: Option<String>,
    /// Optional LoRA adapter ID for per-request fine-tuned inference (SwarmLLM extension).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub lora_adapter: Option<String>,
    /// Optional cache control hints for prefix caching (Anthropic-compatible).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cache_control: Option<CacheControl>,
    /// Catch-all for OpenAI request fields we don't explicitly model
    /// (`reasoning_effort`, `service_tier`, `seed`, `metadata`, `store`,
    /// `parallel_tool_calls`, `stream_options`, `prediction`, …).
    /// `#[serde(flatten)]` preserves them verbatim through the round-trip, so
    /// the cloud-proxy path (handlers::try_cloud_proxy → serde_json::to_value)
    /// forwards the original caller's knobs instead of silently dropping
    /// anything unknown to our struct.
    #[serde(flatten)]
    pub extras: std::collections::HashMap<String, serde_json::Value>,
}

/// Cache control hints for prefix caching (Anthropic-compatible).
#[derive(Debug, Clone, Deserialize, Serialize, Default)]
pub struct CacheControl {
    /// Cache type: "ephemeral" (session-only, default) or "persistent" (longer TTL).
    #[serde(default)]
    pub r#type: Option<String>,
    /// Number of messages from the start to include in the cache prefix.
    /// Default: all system messages.
    #[serde(default)]
    pub prefix_messages: Option<usize>,
}

/// OpenAI-compatible tool definition.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolDefinition {
    #[serde(rename = "type")]
    pub tool_type: String,
    pub function: FunctionDefinition,
}

/// Function definition within a tool.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FunctionDefinition {
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub parameters: Option<serde_json::Value>,
}

/// A tool call generated by the model.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolCall {
    pub id: String,
    #[serde(rename = "type")]
    pub tool_type: String,
    pub function: FunctionCall,
}

/// Function call details within a tool call.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FunctionCall {
    pub name: String,
    pub arguments: String,
}

/// Log probability information for a single token.
#[derive(Debug, Clone, Serialize)]
pub struct TokenLogProb {
    pub token: String,
    pub logprob: f32,
    pub bytes: Option<Vec<u8>>,
    pub top_logprobs: Vec<TopLogProb>,
}

/// A single entry in the top_logprobs array.
#[derive(Debug, Clone, Serialize)]
pub struct TopLogProb {
    pub token: String,
    pub logprob: f32,
    pub bytes: Option<Vec<u8>>,
}

/// Log probability container for a choice.
#[derive(Debug, Clone, Serialize)]
pub struct ChoiceLogProbs {
    pub content: Vec<TokenLogProb>,
}

/// OpenAI-compatible response_format for structured outputs.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum ResponseFormat {
    /// Default text output.
    #[serde(rename = "text")]
    Text,
    /// Model must output valid JSON.
    #[serde(rename = "json_object")]
    JsonObject,
    /// Model output constrained to a JSON schema.
    #[serde(rename = "json_schema")]
    JsonSchema { json_schema: JsonSchemaSpec },
}

/// JSON schema specification for structured output.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct JsonSchemaSpec {
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    pub schema: serde_json::Value,
    #[serde(default)]
    pub strict: bool,
}

/// API-layer chat message supporting OpenAI's multimodal content format.
///
/// The `content` field can be either:
/// - A plain string: `"content": "Hello"`
/// - An array of content parts: `"content": [{"type": "text", "text": "..."}, {"type": "image_url", ...}]`
#[derive(Debug, Serialize, Deserialize)]
pub struct ApiChatMessage {
    pub role: crate::types::Role,
    #[serde(default, deserialize_with = "deserialize_nullable_content")]
    pub content: MessageContent,
    /// Tool calls generated by the assistant (present in assistant messages with tool use).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tool_calls: Option<Vec<ToolCall>>,
    /// The ID of the tool call this message is responding to (present in tool role messages).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tool_call_id: Option<String>,
    /// Tool name (present in tool role messages).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Per-message cache control hint (Anthropic-compatible).
    /// Messages with `{"type": "ephemeral"}` mark the cache breakpoint.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cache_control: Option<CacheControl>,
}

/// OpenAI-compatible content field: either a plain string or an array of content parts.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum MessageContent {
    Text(String),
    Parts(Vec<ContentPart>),
}

/// Deserialize content that can be a string, array of parts, or null.
fn deserialize_nullable_content<'de, D>(deserializer: D) -> Result<MessageContent, D::Error>
where
    D: serde::Deserializer<'de>,
{
    let opt: Option<MessageContent> = Option::deserialize(deserializer)?;
    Ok(opt.unwrap_or_default())
}

impl Default for MessageContent {
    fn default() -> Self {
        Self::Text(String::new())
    }
}

/// A single content part in a multimodal message.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum ContentPart {
    #[serde(rename = "text")]
    Text { text: String },
    #[serde(rename = "image_url")]
    ImageUrl { image_url: ImageUrlRef },
}

/// Image URL reference — supports base64 data URIs.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ImageUrlRef {
    pub url: String,
}

/// Maximum allowed base64-encoded image size (20MB decoded).
const MAX_IMAGE_BASE64_BYTES: usize = 20 * 1024 * 1024;

impl ApiChatMessage {
    /// Convert to the internal `ChatMessage` type, decoding any base64 images.
    pub fn to_chat_message(&self) -> Result<ChatMessage, crate::error::SwarmError> {
        let (text, images) = match &self.content {
            MessageContent::Text(s) => (s.clone(), vec![]),
            MessageContent::Parts(parts) => {
                let mut text_parts = Vec::new();
                let mut images = Vec::new();
                for part in parts {
                    match part {
                        ContentPart::Text { text } => text_parts.push(text.clone()),
                        ContentPart::ImageUrl { image_url } => {
                            let img = decode_image_url(&image_url.url)?;
                            images.push(img);
                        }
                    }
                }
                (text_parts.join("\n"), images)
            }
        };

        Ok(ChatMessage {
            role: self.role.clone(),
            content: text,
            images,
        })
    }
}

impl ChatCompletionRequest {
    /// Convert API messages to internal ChatMessage format, decoding images.
    /// When tools or response_format are provided, injects system message(s).
    pub fn to_internal_messages(&self) -> Result<Vec<ChatMessage>, crate::error::SwarmError> {
        let mut messages: Vec<ChatMessage> = self
            .messages
            .iter()
            .map(|m| m.to_chat_message())
            .collect::<Result<_, _>>()?;

        // Inject structured output instructions
        if let Some(ref fmt) = self.response_format {
            let instruction = match fmt {
                ResponseFormat::Text => None,
                ResponseFormat::JsonObject => Some(
                    "You must respond with valid JSON only. Do not include any text \
                     outside the JSON object. Do not use markdown code blocks."
                        .to_string(),
                ),
                ResponseFormat::JsonSchema { json_schema } => {
                    let schema_str = serde_json::to_string_pretty(&json_schema.schema)
                        .unwrap_or_else(|_| json_schema.schema.to_string());
                    Some(format!(
                        "You must respond with valid JSON that conforms to the following schema. \
                         Do not include any text outside the JSON object. Do not use markdown code blocks.\n\n\
                         Schema name: {}\n\
                         Schema:\n{schema_str}",
                        json_schema.name
                    ))
                }
            };
            if let Some(inst) = instruction {
                messages.insert(
                    0,
                    ChatMessage {
                        role: crate::types::Role::System,
                        content: inst,
                        images: vec![],
                    },
                );
            }
        }

        // Inject tool definitions as a system message prefix — unless the
        // caller asked for no tool use. A local model only knows its tools
        // because they are described here, so "none" has to mean not
        // describing them; there is nowhere else to enforce it.
        if let Some(ref tools) = self.tools {
            if !tools.is_empty()
                && !crate::api::tool_parse::tool_choice_forbids_tools(&self.tool_choice)
            {
                let tool_desc = format_tool_system_prompt(tools);
                messages.insert(
                    0,
                    ChatMessage {
                        role: crate::types::Role::System,
                        content: tool_desc,
                        images: vec![],
                    },
                );
            }
        }

        Ok(messages)
    }

    pub(super) fn to_sampling_params(&self) -> SamplingParams {
        let stop = match &self.stop {
            Some(StopSequence::Single(s)) => vec![s.clone()],
            Some(StopSequence::Multiple(v)) => v.clone(),
            None => vec![],
        };
        crate::api::build_sampling_params(
            self.temperature,
            self.top_p,
            DEFAULT_TOP_K,
            self.max_tokens,
            stop,
            self.frequency_penalty,
            self.presence_penalty,
            self.logprobs,
            self.top_logprobs.unwrap_or(0),
        )
    }
}

/// Format tool definitions into the system prompt that tells a local model how
/// to request a tool call.
///
/// Thin adapter over [`crate::api::tool_parse::format_tool_prompt`], which is
/// shared with the Anthropic surface. The wording must stay identical across
/// both: [`crate::api::tool_parse::parse_tool_calls`] tries the requested shape
/// first, so two wordings would mean two formats to parse. This was a
/// byte-identical copy until 2026-07-26.
pub(super) fn format_tool_system_prompt(tools: &[ToolDefinition]) -> String {
    let specs: Vec<(String, Option<String>, Option<String>)> = tools
        .iter()
        .map(|t| {
            (
                t.function.name.clone(),
                t.function.description.clone(),
                t.function.parameters.as_ref().map(|p| p.to_string()),
            )
        })
        .collect();
    crate::api::tool_parse::format_tool_prompt(&specs)
}

/// Decode a base64 data URI image to raw RGB pixels.
fn decode_image_url(url: &str) -> Result<ImageData, crate::error::SwarmError> {
    let base64_data = if let Some(rest) = url.strip_prefix("data:") {
        if let Some(comma_pos) = rest.find(',') {
            let header = &rest[..comma_pos];
            if !header.contains("base64") {
                return Err(crate::error::SwarmError::Validation(
                    "Only base64 data URIs are supported for image_url".into(),
                ));
            }
            &rest[comma_pos + 1..]
        } else {
            return Err(crate::error::SwarmError::Validation(
                "Invalid data URI format".into(),
            ));
        }
    } else {
        return Err(crate::error::SwarmError::Validation(
            "Only data: URIs are supported for image_url (not remote URLs)".into(),
        ));
    };

    if base64_data.len() > MAX_IMAGE_BASE64_BYTES * 4 / 3 + 4 {
        return Err(crate::error::SwarmError::Validation(format!(
            "Image too large (max {}MB)",
            MAX_IMAGE_BASE64_BYTES / (1024 * 1024)
        )));
    }

    use base64::Engine;
    let bytes = base64::engine::general_purpose::STANDARD
        .decode(base64_data)
        .map_err(|e| crate::error::SwarmError::Validation(format!("Invalid base64 image: {e}")))?;

    if bytes.len() > MAX_IMAGE_BASE64_BYTES {
        return Err(crate::error::SwarmError::Validation(format!(
            "Decoded image too large: {}MB (max {}MB)",
            bytes.len() / (1024 * 1024),
            MAX_IMAGE_BASE64_BYTES / (1024 * 1024)
        )));
    }

    let img = image::load_from_memory(&bytes).map_err(|e| {
        crate::error::SwarmError::Validation(format!("Failed to decode image: {e}"))
    })?;

    let rgb = img.to_rgb8();
    let (width, height) = (rgb.width(), rgb.height());

    Ok(ImageData {
        rgb_bytes: rgb.into_raw(),
        width,
        height,
    })
}

#[derive(Debug, Serialize, Deserialize)]
#[serde(untagged)]
pub enum StopSequence {
    Single(String),
    Multiple(Vec<String>),
}

fn default_temperature() -> f32 {
    0.7
}
fn default_top_p() -> f32 {
    0.9
}
fn default_max_tokens() -> u32 {
    2048
}

// ---- Response types (OpenAI-compatible) ----

#[derive(Debug, Serialize)]
pub struct ChatCompletionResponse {
    pub id: String,
    pub object: &'static str,
    pub created: i64,
    pub model: String,
    pub choices: Vec<ChatChoice>,
    pub usage: Usage,
    /// Session ID for multi-turn KV-cache reuse. Echoed from the request
    /// or auto-generated. Clients should pass this back in subsequent
    /// requests to reuse cached KV state and skip redundant prefill.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub session_id: Option<String>,
}

#[derive(Debug, Serialize)]
pub struct ChatChoice {
    pub index: u32,
    pub message: ChatMessageResponse,
    pub finish_reason: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub logprobs: Option<ChoiceLogProbs>,
}

#[derive(Debug, Serialize)]
pub struct ChatMessageResponse {
    pub role: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tool_calls: Option<Vec<ToolCall>>,
}

#[derive(Debug, Serialize)]
pub struct Usage {
    pub prompt_tokens: u32,
    pub completion_tokens: u32,
    pub total_tokens: u32,
    /// Number of prompt tokens used to create a new cache entry.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cache_creation_input_tokens: Option<u32>,
    /// Number of prompt tokens read from an existing cache entry.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cache_read_input_tokens: Option<u32>,
}

impl Usage {
    pub fn from_counts(prompt_tokens: u32, completion_tokens: u32) -> Self {
        Self {
            prompt_tokens,
            completion_tokens,
            total_tokens: prompt_tokens + completion_tokens,
            cache_creation_input_tokens: None,
            cache_read_input_tokens: None,
        }
    }
}

#[derive(Debug, Serialize)]
pub struct ChatCompletionChunk {
    pub id: String,
    pub object: &'static str,
    pub created: i64,
    pub model: String,
    pub choices: Vec<ChunkChoice>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub session_id: Option<String>,
    /// OpenAI 2024+ spec: when the request includes
    /// `stream_options: {"include_usage": true}`, an extra terminal chunk
    /// is emitted with `choices: []` and this field populated. Skipped on
    /// every intermediate chunk so existing clients see no change.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub usage: Option<Usage>,
}

#[derive(Debug, Serialize)]
pub struct ChunkChoice {
    pub index: u32,
    pub delta: Delta,
    pub finish_reason: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub logprobs: Option<ChoiceLogProbs>,
}

#[derive(Debug, Serialize)]
pub struct Delta {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub role: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tool_calls: Option<Vec<StreamToolCall>>,
}

/// Tool call in a streaming delta (includes index for reassembly).
#[derive(Debug, Clone, Serialize)]
pub struct StreamToolCall {
    pub index: u32,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub tool_type: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub function: Option<StreamFunctionCall>,
}

/// Function call fragment in a streaming tool call delta.
#[derive(Debug, Clone, Serialize)]
pub struct StreamFunctionCall {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub arguments: Option<String>,
}

// ---- Model list types ----

#[derive(Debug, Serialize)]
pub struct ModelListResponse {
    pub object: &'static str,
    pub data: Vec<ModelInfo>,
}

#[derive(Debug, Serialize)]
pub struct ModelInfo {
    pub id: String,
    pub object: &'static str,
    pub created: i64,
    pub owned_by: String,
    /// Longest conversation this node will actually serve for the model, in
    /// tokens — prompt plus reply, after the shipped cap and any
    /// `inference.max_seq_len_override`.
    ///
    /// Not part of OpenAI's own schema, but the field vLLM added for exactly
    /// this reason, so OpenAI-compatible clients already look for it and the
    /// rest ignore an unknown key. Omitted when the model's declared context
    /// cannot be read rather than guessed at, since a wrong number here is
    /// worse than none.
    ///
    /// Reported 2026-08-10: with nothing advertised, a client registered a
    /// 32k-capable model at its full length against a node serving 4096, and
    /// the mismatch surfaced as a request with "no room for any prompt at all".
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_model_len: Option<usize>,
    /// The same figure under the name OpenClaw's self-hosted model discovery
    /// reads. Its discovery looks for `context_length`, `context_window` or
    /// `context_size` and, finding none, assumes **128,000** — so a client that
    /// was told nothing sent prompts sized for 128k to a node serving 8192 and
    /// was refused every time (researched 2026-09-02; `max_model_len` is only
    /// consulted by its generic live-catalog path, not the self-hosted one).
    /// Always equal to `max_model_len`, which `ModelInfo::new` guarantees;
    /// never set one without the other.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub context_length: Option<usize>,
}

impl ModelInfo {
    /// Build an entry whose two context fields cannot disagree.
    ///
    /// `effective_context` is the longest conversation this node will serve,
    /// or `None` when the model's declared context cannot be read — in which
    /// case BOTH fields are omitted rather than guessed.
    pub fn new(
        id: String,
        created: i64,
        owned_by: String,
        effective_context: Option<usize>,
    ) -> Self {
        Self {
            id,
            object: "model",
            created,
            owned_by,
            max_model_len: effective_context,
            context_length: effective_context,
        }
    }
}

// ---- Embeddings request/response ----

#[derive(Debug, Deserialize)]
pub struct EmbeddingRequest {
    pub model: String,
    pub input: EmbeddingInput,
    #[serde(default = "default_encoding_format")]
    pub encoding_format: String,
}

#[derive(Debug, Deserialize)]
#[serde(untagged)]
pub enum EmbeddingInput {
    Single(String),
    Batch(Vec<String>),
}

fn default_encoding_format() -> String {
    "float".into()
}
