use axum::extract::State;
use axum::response::sse::{Event, KeepAlive, Sse};
use axum::response::IntoResponse;
use axum::Json;
use futures::stream::Stream;
use serde::{Deserialize, Serialize};
use std::convert::Infallible;
use tokio_stream::StreamExt;

use crate::api::server::AppState;
use crate::error::ApiError;
use crate::inference::chat_template;
use crate::inference::router::{RouterCommand, StreamingTokenEvent};
use crate::types::{ChatMessage, ImageData, InferenceRequest, ModelId, SamplingParams};

/// Timeout for peer-forwarded inference requests (seconds).
const INFERENCE_FORWARD_TIMEOUT_SECS: u64 = 120;

use super::{DEFAULT_MAX_TOKENS, DEFAULT_TOP_K, SSE_KEEPALIVE_INTERVAL_SECS};

/// Maximum cold-start wait time before returning 503 (seconds).
const COLD_START_WAIT_SECS: u32 = 10;

/// Maximum number of concurrent requests in the cold-start polling loop.
/// Prevents unbounded task pile-up when many requests arrive for unavailable models.
const MAX_COLD_START_SLOTS: usize = 5;
static COLD_START_SEMAPHORE: std::sync::LazyLock<tokio::sync::Semaphore> =
    std::sync::LazyLock::new(|| tokio::sync::Semaphore::new(MAX_COLD_START_SLOTS));

// ---- Request types ----

#[derive(Debug, Serialize, Deserialize)]
pub struct ChatCompletionRequest {
    pub model: String,
    pub messages: Vec<ApiChatMessage>,
    #[serde(default = "default_temperature")]
    pub temperature: f32,
    #[serde(default = "default_top_p")]
    pub top_p: f32,
    #[serde(default = "default_max_tokens")]
    pub max_tokens: u32,
    #[serde(default)]
    pub stream: bool,
    #[serde(default)]
    pub stop: Option<StopSequence>,
    #[serde(default)]
    pub frequency_penalty: f32,
    #[serde(default)]
    pub presence_penalty: f32,
    /// Tool definitions for function calling (OpenAI-compatible).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tools: Option<Vec<ToolDefinition>>,
    /// Controls which tool the model calls: "none", "auto", or {"type":"function","function":{"name":"..."}}.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tool_choice: Option<serde_json::Value>,
    /// Whether to return log probabilities for output tokens.
    #[serde(default)]
    pub logprobs: bool,
    /// Number of top log probabilities to return per token (0-20). Requires logprobs=true.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub top_logprobs: Option<u32>,
    /// Structured output format. Supports:
    /// - `{"type": "json_object"}` — model outputs valid JSON
    /// - `{"type": "json_schema", "json_schema": {"name": "...", "schema": {...}}}` — constrained to schema
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub response_format: Option<ResponseFormat>,
    /// Optional session ID for multi-turn KV-cache reuse.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub session_id: Option<String>,
    /// Optional LoRA adapter ID for per-request fine-tuned inference (SwarmLLM extension).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub lora_adapter: Option<String>,
    /// Optional cache control hints for prefix caching (Anthropic-compatible).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cache_control: Option<CacheControl>,
}

/// Cache control hints for prefix caching (Anthropic-compatible).
#[derive(Debug, Clone, Deserialize, Serialize, Default)]
pub struct CacheControl {
    /// Cache type: "ephemeral" (session-only, default) or "persistent" (longer TTL).
    #[serde(default)]
    pub r#type: Option<String>,
    /// Number of messages from the start to include in the cache prefix.
    /// Default: all system messages.
    #[serde(default)]
    pub prefix_messages: Option<usize>,
}

/// OpenAI-compatible tool definition.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolDefinition {
    #[serde(rename = "type")]
    pub tool_type: String,
    pub function: FunctionDefinition,
}

/// Function definition within a tool.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FunctionDefinition {
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub parameters: Option<serde_json::Value>,
}

/// A tool call generated by the model.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolCall {
    pub id: String,
    #[serde(rename = "type")]
    pub tool_type: String,
    pub function: FunctionCall,
}

/// Function call details within a tool call.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FunctionCall {
    pub name: String,
    pub arguments: String,
}

/// Log probability information for a single token.
#[derive(Debug, Clone, Serialize)]
pub struct TokenLogProb {
    pub token: String,
    pub logprob: f32,
    pub bytes: Option<Vec<u8>>,
    pub top_logprobs: Vec<TopLogProb>,
}

/// A single entry in the top_logprobs array.
#[derive(Debug, Clone, Serialize)]
pub struct TopLogProb {
    pub token: String,
    pub logprob: f32,
    pub bytes: Option<Vec<u8>>,
}

/// Log probability container for a choice.
#[derive(Debug, Clone, Serialize)]
pub struct ChoiceLogProbs {
    pub content: Vec<TokenLogProb>,
}

/// OpenAI-compatible response_format for structured outputs.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum ResponseFormat {
    /// Default text output.
    #[serde(rename = "text")]
    Text,
    /// Model must output valid JSON.
    #[serde(rename = "json_object")]
    JsonObject,
    /// Model output constrained to a JSON schema.
    #[serde(rename = "json_schema")]
    JsonSchema { json_schema: JsonSchemaSpec },
}

/// JSON schema specification for structured output.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct JsonSchemaSpec {
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    pub schema: serde_json::Value,
    #[serde(default)]
    pub strict: bool,
}

/// API-layer chat message supporting OpenAI's multimodal content format.
///
/// The `content` field can be either:
/// - A plain string: `"content": "Hello"`
/// - An array of content parts: `"content": [{"type": "text", "text": "..."}, {"type": "image_url", ...}]`
#[derive(Debug, Serialize, Deserialize)]
pub struct ApiChatMessage {
    pub role: crate::types::Role,
    #[serde(default, deserialize_with = "deserialize_nullable_content")]
    pub content: MessageContent,
    /// Tool calls generated by the assistant (present in assistant messages with tool use).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tool_calls: Option<Vec<ToolCall>>,
    /// The ID of the tool call this message is responding to (present in tool role messages).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tool_call_id: Option<String>,
    /// Tool name (present in tool role messages).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Per-message cache control hint (Anthropic-compatible).
    /// Messages with `{"type": "ephemeral"}` mark the cache breakpoint.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cache_control: Option<CacheControl>,
}

/// OpenAI-compatible content field: either a plain string or an array of content parts.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum MessageContent {
    Text(String),
    Parts(Vec<ContentPart>),
}

/// Deserialize content that can be a string, array of parts, or null.
fn deserialize_nullable_content<'de, D>(deserializer: D) -> Result<MessageContent, D::Error>
where
    D: serde::Deserializer<'de>,
{
    let opt: Option<MessageContent> = Option::deserialize(deserializer)?;
    Ok(opt.unwrap_or_default())
}

impl Default for MessageContent {
    fn default() -> Self {
        Self::Text(String::new())
    }
}

/// A single content part in a multimodal message.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum ContentPart {
    #[serde(rename = "text")]
    Text { text: String },
    #[serde(rename = "image_url")]
    ImageUrl { image_url: ImageUrlRef },
}

/// Image URL reference — supports base64 data URIs.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ImageUrlRef {
    pub url: String,
}

/// Maximum allowed base64-encoded image size (20MB decoded).
const MAX_IMAGE_BASE64_BYTES: usize = 20 * 1024 * 1024;

impl ApiChatMessage {
    /// Convert to the internal `ChatMessage` type, decoding any base64 images.
    pub fn to_chat_message(&self) -> Result<ChatMessage, crate::error::SwarmError> {
        let (text, images) = match &self.content {
            MessageContent::Text(s) => (s.clone(), vec![]),
            MessageContent::Parts(parts) => {
                let mut text_parts = Vec::new();
                let mut images = Vec::new();
                for part in parts {
                    match part {
                        ContentPart::Text { text } => text_parts.push(text.clone()),
                        ContentPart::ImageUrl { image_url } => {
                            let img = decode_image_url(&image_url.url)?;
                            images.push(img);
                        }
                    }
                }
                (text_parts.join("\n"), images)
            }
        };

        Ok(ChatMessage {
            role: self.role.clone(),
            content: text,
            images,
        })
    }
}

impl ChatCompletionRequest {
    /// Convert API messages to internal ChatMessage format, decoding images.
    /// When tools or response_format are provided, injects system message(s).
    pub fn to_internal_messages(&self) -> Result<Vec<ChatMessage>, crate::error::SwarmError> {
        let mut messages: Vec<ChatMessage> = self
            .messages
            .iter()
            .map(|m| m.to_chat_message())
            .collect::<Result<_, _>>()?;

        // Inject structured output instructions
        if let Some(ref fmt) = self.response_format {
            let instruction = match fmt {
                ResponseFormat::Text => None,
                ResponseFormat::JsonObject => Some(
                    "You must respond with valid JSON only. Do not include any text \
                     outside the JSON object. Do not use markdown code blocks."
                        .to_string(),
                ),
                ResponseFormat::JsonSchema { json_schema } => {
                    let schema_str = serde_json::to_string_pretty(&json_schema.schema)
                        .unwrap_or_else(|_| json_schema.schema.to_string());
                    Some(format!(
                        "You must respond with valid JSON that conforms to the following schema. \
                         Do not include any text outside the JSON object. Do not use markdown code blocks.\n\n\
                         Schema name: {}\n\
                         Schema:\n{schema_str}",
                        json_schema.name
                    ))
                }
            };
            if let Some(inst) = instruction {
                messages.insert(
                    0,
                    ChatMessage {
                        role: crate::types::Role::System,
                        content: inst,
                        images: vec![],
                    },
                );
            }
        }

        // Inject tool definitions as a system message prefix
        if let Some(ref tools) = self.tools {
            if !tools.is_empty() {
                let tool_desc = format_tool_system_prompt(tools);
                messages.insert(
                    0,
                    ChatMessage {
                        role: crate::types::Role::System,
                        content: tool_desc,
                        images: vec![],
                    },
                );
            }
        }

        Ok(messages)
    }
}

/// Format tool definitions into a system prompt that instructs the model
/// to output tool calls in a structured JSON format.
fn format_tool_system_prompt(tools: &[ToolDefinition]) -> String {
    let mut prompt = String::from(
        "You have access to the following tools. To call a tool, respond with a JSON object \
         in the following format:\n\
         {\"tool_calls\": [{\"id\": \"call_<unique_id>\", \"type\": \"function\", \
         \"function\": {\"name\": \"<function_name>\", \"arguments\": \"<json_args>\"}}]}\n\n\
         Available tools:\n",
    );
    for tool in tools {
        prompt.push_str(&format!("- {}", tool.function.name));
        if let Some(ref desc) = tool.function.description {
            prompt.push_str(&format!(": {desc}"));
        }
        prompt.push('\n');
        if let Some(ref params) = tool.function.parameters {
            prompt.push_str(&format!("  Parameters: {params}\n"));
        }
    }
    prompt
}

/// Decode a base64 data URI image to raw RGB pixels.
fn decode_image_url(url: &str) -> Result<ImageData, crate::error::SwarmError> {
    let base64_data = if let Some(rest) = url.strip_prefix("data:") {
        if let Some(comma_pos) = rest.find(',') {
            let header = &rest[..comma_pos];
            if !header.contains("base64") {
                return Err(crate::error::SwarmError::Validation(
                    "Only base64 data URIs are supported for image_url".into(),
                ));
            }
            &rest[comma_pos + 1..]
        } else {
            return Err(crate::error::SwarmError::Validation(
                "Invalid data URI format".into(),
            ));
        }
    } else {
        return Err(crate::error::SwarmError::Validation(
            "Only data: URIs are supported for image_url (not remote URLs)".into(),
        ));
    };

    if base64_data.len() > MAX_IMAGE_BASE64_BYTES * 4 / 3 + 4 {
        return Err(crate::error::SwarmError::Validation(format!(
            "Image too large (max {}MB)",
            MAX_IMAGE_BASE64_BYTES / (1024 * 1024)
        )));
    }

    use base64::Engine;
    let bytes = base64::engine::general_purpose::STANDARD
        .decode(base64_data)
        .map_err(|e| crate::error::SwarmError::Validation(format!("Invalid base64 image: {e}")))?;

    if bytes.len() > MAX_IMAGE_BASE64_BYTES {
        return Err(crate::error::SwarmError::Validation(format!(
            "Decoded image too large: {}MB (max {}MB)",
            bytes.len() / (1024 * 1024),
            MAX_IMAGE_BASE64_BYTES / (1024 * 1024)
        )));
    }

    let img = image::load_from_memory(&bytes).map_err(|e| {
        crate::error::SwarmError::Validation(format!("Failed to decode image: {e}"))
    })?;

    let rgb = img.to_rgb8();
    let (width, height) = (rgb.width(), rgb.height());

    Ok(ImageData {
        rgb_bytes: rgb.into_raw(),
        width,
        height,
    })
}

#[derive(Debug, Serialize, Deserialize)]
#[serde(untagged)]
pub enum StopSequence {
    Single(String),
    Multiple(Vec<String>),
}

fn default_temperature() -> f32 {
    0.7
}
fn default_top_p() -> f32 {
    0.9
}
fn default_max_tokens() -> u32 {
    2048
}

impl ChatCompletionRequest {
    fn to_sampling_params(&self) -> SamplingParams {
        let stop = match &self.stop {
            Some(StopSequence::Single(s)) => vec![s.clone()],
            Some(StopSequence::Multiple(v)) => v.clone(),
            None => vec![],
        };
        SamplingParams {
            // Clamp temperature to [0.0, 2.0] to prevent invalid values
            temperature: self.temperature.clamp(0.0, 2.0),
            // Clamp top_p to (0.0, 1.0]
            top_p: self.top_p.clamp(f32::EPSILON, 1.0),
            top_k: DEFAULT_TOP_K,
            max_tokens: self.max_tokens.clamp(1, DEFAULT_MAX_TOKENS),
            stop,
            frequency_penalty: self.frequency_penalty.clamp(-2.0, 2.0),
            presence_penalty: self.presence_penalty.clamp(-2.0, 2.0),
            logprobs: self.logprobs,
            top_logprobs: self.top_logprobs.unwrap_or(0).min(20),
        }
    }
}

// ---- Response types (OpenAI-compatible) ----

#[derive(Debug, Serialize)]
pub struct ChatCompletionResponse {
    pub id: String,
    pub object: &'static str,
    pub created: i64,
    pub model: String,
    pub choices: Vec<ChatChoice>,
    pub usage: Usage,
    /// Session ID for multi-turn KV-cache reuse. Echoed from the request
    /// or auto-generated. Clients should pass this back in subsequent
    /// requests to reuse cached KV state and skip redundant prefill.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub session_id: Option<String>,
}

#[derive(Debug, Serialize)]
pub struct ChatChoice {
    pub index: u32,
    pub message: ChatMessageResponse,
    pub finish_reason: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub logprobs: Option<ChoiceLogProbs>,
}

#[derive(Debug, Serialize)]
pub struct ChatMessageResponse {
    pub role: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tool_calls: Option<Vec<ToolCall>>,
}

#[derive(Debug, Serialize)]
pub struct Usage {
    pub prompt_tokens: u32,
    pub completion_tokens: u32,
    pub total_tokens: u32,
    /// Number of prompt tokens used to create a new cache entry.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cache_creation_input_tokens: Option<u32>,
    /// Number of prompt tokens read from an existing cache entry.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cache_read_input_tokens: Option<u32>,
}

#[derive(Debug, Serialize)]
pub struct ChatCompletionChunk {
    pub id: String,
    pub object: &'static str,
    pub created: i64,
    pub model: String,
    pub choices: Vec<ChunkChoice>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub session_id: Option<String>,
}

#[derive(Debug, Serialize)]
pub struct ChunkChoice {
    pub index: u32,
    pub delta: Delta,
    pub finish_reason: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub logprobs: Option<ChoiceLogProbs>,
}

#[derive(Debug, Serialize)]
pub struct Delta {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub role: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tool_calls: Option<Vec<StreamToolCall>>,
}

/// Tool call in a streaming delta (includes index for reassembly).
#[derive(Debug, Clone, Serialize)]
pub struct StreamToolCall {
    pub index: u32,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub tool_type: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub function: Option<StreamFunctionCall>,
}

/// Function call fragment in a streaming tool call delta.
#[derive(Debug, Clone, Serialize)]
pub struct StreamFunctionCall {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub arguments: Option<String>,
}

// ---- Model list types ----

#[derive(Debug, Serialize)]
pub struct ModelListResponse {
    pub object: &'static str,
    pub data: Vec<ModelInfo>,
}

#[derive(Debug, Serialize)]
pub struct ModelInfo {
    pub id: String,
    pub object: &'static str,
    pub created: i64,
    pub owned_by: String,
}

// ---- Handlers ----

/// POST /v1/chat/completions
/// Validate and sanitize a chat completion request.
/// Checks session_id, model, messages, temperature, content sizes, tools, stop sequences.
/// Binds session_id to caller's API key to prevent cross-user KV-cache hijacking.
fn validate_chat_request(
    req: &mut ChatCompletionRequest,
    headers: &axum::http::HeaderMap,
) -> Result<(), ApiError> {
    // Validate session_id length to prevent memory abuse
    if let Some(ref sid) = req.session_id {
        if sid.len() > 256 {
            return Err(ApiError(crate::error::SwarmError::Validation(
                "session_id too long (max 256 chars)".into(),
            )));
        }
    }

    // Bind session_id to the caller's API key so different users cannot
    // hijack each other's KV-cache sessions by guessing session IDs.
    if let Some(ref mut sid) = req.session_id {
        let api_key = super::extract_bearer_token(headers);
        let key_hash = &blake3::hash(api_key.as_bytes()).to_hex()[..16];
        *sid = format!("{}:{}", key_hash, sid);
    }

    super::validate_common_params(req.model.len(), req.messages.len(), req.temperature.into())?;

    // SEC: Cap individual message content size and total prompt size
    super::validate_content_size(req.messages.iter().map(|msg| {
        match &msg.content {
            MessageContent::Text(s) => s.len(),
            MessageContent::Parts(parts) => parts
                .iter()
                .map(|p| match p {
                    ContentPart::Text { text } => text.len(),
                    ContentPart::ImageUrl { image_url } => image_url.url.len(),
                })
                .sum(),
        }
    }))?;

    if let Some(ref tools) = req.tools {
        super::validate_tools(
            tools,
            |t| Some(t.function.name.as_str()),
            |t| t.function.description.as_deref(),
            |t| t.function.parameters.as_ref().map(|p| p.to_string().len()),
        )?;
    }

    if let Some(ref adapter) = req.lora_adapter {
        if adapter.len() > 256 {
            return Err(ApiError(crate::error::SwarmError::Validation(
                "lora_adapter name too long (max 256 chars)".into(),
            )));
        }
        if adapter.contains("..") || adapter.contains('/') || adapter.contains('\\') {
            return Err(ApiError(crate::error::SwarmError::Validation(
                "lora_adapter contains invalid characters".into(),
            )));
        }
    }

    match &req.stop {
        Some(crate::api::openai::StopSequence::Multiple(v)) => {
            super::validate_stop_sequences(v)?;
        }
        Some(crate::api::openai::StopSequence::Single(s)) => {
            super::validate_stop_sequences(std::slice::from_ref(s))?;
        }
        None => {}
    }

    Ok(())
}

/// Try proxying a chat completion request to a configured cloud provider.
async fn try_cloud_proxy(
    state: &AppState,
    req: &ChatCompletionRequest,
) -> Result<Option<axum::response::Response>, ApiError> {
    // Claude subscription: proxy through local CLI subprocess (higher priority than API key)
    #[cfg(feature = "claude-subscription")]
    if let Some(sub_config) =
        crate::api::claude_sub::try_get_claude_subscription(state, &req.model).await
    {
        tracing::info!(model = %req.model, "DIAG: openai proxying via claude subscription subprocess");
        let body = serde_json::to_value(req).map_err(|e| {
            ApiError(crate::error::SwarmError::Validation(format!(
                "serialize request: {e}"
            )))
        })?;
        return crate::api::claude_sub::proxy_via_subprocess_openai(&sub_config, &body)
            .await
            .map(Some);
    }

    let body = serde_json::to_value(req).map_err(|e| {
        ApiError(crate::error::SwarmError::Validation(format!(
            "serialize request: {e}"
        )))
    })?;
    crate::api::providers::try_proxy_openai(state, &body, req.stream).await
}

pub async fn chat_completions(
    State(state): State<AppState>,
    headers: axum::http::HeaderMap,
    crate::api::server::JsonBody(mut req): crate::api::server::JsonBody<ChatCompletionRequest>,
) -> Result<axum::response::Response, ApiError> {
    validate_chat_request(&mut req, &headers)?;

    // Convert API messages to internal format (decode base64 images if present)
    let internal_messages = req.to_internal_messages().map_err(ApiError)?;

    let request_id = format!("swarm-{}", uuid::Uuid::new_v4().simple());
    let created = chrono::Utc::now().timestamp();

    // Track requests made by this node
    super::increment_requests_made(&state.shared_state);

    // Emit activity event for inference request
    {
        let mname = state
            .shared_state
            .model_registry
            .get_manifest(&crate::types::ModelId(req.model.clone()))
            .map(|m| m.name.clone());
        let display = mname.as_deref().unwrap_or(&req.model);
        let max_tok = req.max_tokens;
        let msg_count = req.messages.len();
        let prompt_preview: String = req
            .messages
            .last()
            .map(|m| {
                let content = match &m.content {
                    crate::api::openai::MessageContent::Text(s) => s.clone(),
                    crate::api::openai::MessageContent::Parts(parts) => parts
                        .iter()
                        .filter_map(|p| match p {
                            crate::api::openai::ContentPart::Text { text } => Some(text.as_str()),
                            _ => None,
                        })
                        .collect::<Vec<_>>()
                        .join(" "),
                };
                if content.len() > 60 {
                    format!(
                        "{}...",
                        &content[..content
                            .char_indices()
                            .take_while(|(i, _)| *i < 57)
                            .last()
                            .map(|(i, c)| i + c.len_utf8())
                            .unwrap_or(57)]
                    )
                } else {
                    content
                }
            })
            .unwrap_or_default();
        state.shared_state.emit_activity(
            crate::daemon::state::ActivityEvent::new(
                "inference",
                "inference_request",
                format!(
                    "Inference request on {} — {} message{}, max {} tokens{}",
                    display,
                    msg_count,
                    if msg_count != 1 { "s" } else { "" },
                    max_tok,
                    if !prompt_preview.is_empty() {
                        format!(": \"{}\"", prompt_preview)
                    } else {
                        String::new()
                    }
                ),
            )
            .with_model(req.model.clone())
            .with_detail_num(max_tok as i64),
        );
    }

    // Resolve "auto" alias and display-name → registry-ID mapping.
    {
        let resolved = resolve_model_for_inference(&state, &req.model).await;
        if resolved != req.model {
            tracing::info!(original = %req.model, resolved_model = %resolved, "Resolved model alias");
            req.model = resolved;
        }
    }

    let image_count: usize = internal_messages.iter().map(|m| m.images.len()).sum();
    tracing::info!(
        request_id = %request_id,
        model = %req.model,
        messages = internal_messages.len(),
        images = image_count,
        stream = req.stream,
        "Chat completion request"
    );

    // Get model name — try loaded_model_info cache first, then manifest registry.
    let model_name = resolve_model_name(&state, &req.model).await;

    // No local full-model executor — use distributed inference or forward.
    // Nodes are NOT required to have all shards. Any node can initiate inference
    // as long as the network collectively covers all layers.
    // The `x-swarm-forwarded` header prevents infinite forwarding loops between nodes.
    // Only trust this header from internal requests (authenticated with internal token).
    // Middleware already validates that x-swarm-forwarded only passes from known peer IPs
    // or loopback with valid internal token, so we just check presence here.
    let is_forwarded = headers.get("x-swarm-forwarded").is_some();

    if model_name.is_none() {
        // Priority 1: Check if all layers are covered across the network for
        // distributed inference. The local node may have zero, some, or all shards —
        // it doesn't matter as long as the network covers every layer.
        if all_shards_available(&state, &req.model) {
            tracing::info!(
                request_id = %request_id,
                model = %req.model,
                stream = req.stream,
                "All layers covered across network — using distributed inference"
            );

            if let Some(router_tx) = &state.router_tx {
                return dispatch_inference(
                    router_tx.clone(),
                    &state,
                    &req,
                    internal_messages.clone(),
                    request_id,
                    created,
                )
                .await;
            } else {
                return Err(ApiError(crate::error::SwarmError::NoModelLoaded));
            }
        }

        // Priority 2: Forward to a peer that hosts shards for this model.
        // That peer can handle inference locally or build its own pipeline.
        if !is_forwarded {
            if let Some(peer_url) = find_peer_with_model(&state, &req.model) {
                tracing::info!(
                    request_id = %request_id,
                    peer_url = %peer_url,
                    "Forwarding request to peer"
                );
                return forward_to_peer(&peer_url, &req, req.stream).await;
            }
        }

        // Cloud provider fast-path: if the model matches a configured cloud provider,
        // route immediately without cold-start waiting. Cloud models are never local.
        if let Some(response) = try_cloud_proxy(&state, &req).await? {
            return Ok(response);
        }

        // Fast-reject: if the model has no manifest but other models ARE registered,
        // the user likely mistyped. Return ModelNotAvailable immediately instead of
        // wasting 10 seconds on cold-start polling. When NO models are registered,
        // fall through to the cold-start wait (node may still be starting up).
        {
            let model_id = crate::types::ModelId(req.model.clone());
            let registry = &state.shared_state.model_registry;
            if registry.get_manifest(&model_id).is_none() && !registry.models().is_empty() {
                return Err(ApiError(registry.model_not_found_error(&model_id)));
            }
        }

        // Cold-start wait: shard announcements may still be propagating.
        // Poll for up to 10 seconds before giving up.
        // Semaphore prevents unbounded pile-up under burst traffic.
        let _cold_permit = match COLD_START_SEMAPHORE.try_acquire() {
            Ok(permit) => permit,
            Err(_) => {
                tracing::warn!(
                    request_id = %request_id,
                    model = %req.model,
                    "Cold-start wait slots full — returning 503 immediately"
                );
                return Err(ApiError(crate::error::SwarmError::NoModelLoaded));
            }
        };
        let max_polls = COLD_START_WAIT_SECS * 2; // 500ms intervals
        for attempt in 1..=max_polls {
            tokio::time::sleep(std::time::Duration::from_millis(500)).await;
            // Re-check distributed inference availability
            if all_shards_available(&state, &req.model) {
                tracing::info!(
                    request_id = %request_id,
                    model = %req.model,
                    wait_ms = attempt * 500,
                    "Model became available after cold-start wait"
                );
                if let Some(router_tx) = &state.router_tx {
                    return dispatch_inference(
                        router_tx.clone(),
                        &state,
                        &req,
                        internal_messages.clone(),
                        request_id,
                        created,
                    )
                    .await;
                }
                break;
            }
            // Re-check peer forwarding
            if !is_forwarded {
                if let Some(peer_url) = find_peer_with_model(&state, &req.model) {
                    tracing::info!(
                        request_id = %request_id,
                        peer_url = %peer_url,
                        wait_ms = attempt * 500,
                        "Found peer after cold-start wait"
                    );
                    return forward_to_peer(&peer_url, &req, req.stream).await;
                }
            }
        }

        // Cloud provider fallback: proxy to configured cloud provider if model matches
        if let Some(response) = try_cloud_proxy(&state, &req).await? {
            return Ok(response);
        }

        return Err(ApiError(crate::error::SwarmError::NoModelLoaded));
    }

    let model_name =
        model_name.expect("model_name guaranteed Some — None case returns early above");
    let params = req.to_sampling_params();

    // Fast path: if we have a complete local split model (all layers), generate directly.
    // This avoids the distributed pipeline overhead (per-token segment coordination,
    // activation serialization, mutex per token). ~5-10x faster for local inference.
    // Uses the pre-computed is_complete flag — no model mutex needed.
    // Look up by the REQUESTED model ID, not just the first entry.
    // NOTE: prompt is built inside split_*_response using the model's own chat template,
    // avoiding template mismatch (e.g. `<|assistant|>` prefix leak) and the unnecessary
    // loaded_model_info.read().await before the split path.
    let requested_mid = crate::types::ModelId(req.model.clone());
    let has_local_split_model = state.shared_state.has_complete_split_model(&requested_mid);

    if has_local_split_model {
        if req.stream {
            return Ok(split_stream_response(
                state,
                request_id,
                created,
                model_name,
                internal_messages.clone(),
                params,
                requested_mid.clone(),
            )
            .await
            .into_response());
        } else {
            return split_non_stream_response(
                state,
                request_id,
                created,
                model_name,
                internal_messages.clone(),
                params,
                requested_mid.clone(),
            )
            .await;
        }
    }

    // Build prompt for non-split paths (distributed inference + direct executor).
    // Uses loaded_model_info first; falls back to GGUF header on disk for
    // distributed-only nodes that have no local model but do have the probe.
    let prompt = {
        let (tmpl, bos, eos) = super::resolve_chat_template(&state, &req.model).await;
        chat_template::build_prompt(&internal_messages, tmpl.as_deref(), &bos, &eos)
    };

    // Distributed inference: network covers all layers across multiple nodes.
    let peers_have_shards = all_shards_available(&state, &req.model)
        || state.shared_state.config.inference.shard_range.is_some();
    if peers_have_shards {
        if let Some(router_tx) = &state.router_tx {
            return dispatch_inference(
                router_tx.clone(),
                &state,
                &req,
                internal_messages.clone(),
                request_id,
                created,
            )
            .await;
        }
    }

    if req.stream {
        // Streaming: use direct executor path for real token-by-token SSE
        Ok(
            stream_response(state, request_id, created, model_name, prompt, params)
                .await
                .into_response(),
        )
    } else if let Some(router_tx) = &state.router_tx {
        // Non-streaming: route through InferenceRouter for priority queueing
        router_inference(
            router_tx.clone(),
            &req,
            internal_messages,
            request_id,
            created,
        )
        .await
    } else {
        Err(crate::error::ApiError(
            crate::error::SwarmError::ServiceUnavailable(
                "Inference router not available".to_string(),
            ),
        ))
    }
}

/// Find a peer that hosts shards for this model and return its HTTP base URL.
/// This is a fallback for when not all layers are covered network-wide — the
/// peer may be able to handle the request directly or assemble its own pipeline.
fn find_peer_with_model(state: &AppState, model: &str) -> Option<String> {
    for entry in state.shared_state.peer_registry.iter() {
        let peer = entry.value();
        if let Some(ref cap) = peer.capability {
            let has_model = cap.hosted_shards.iter().any(|s| s.model_id.0 == model);
            if has_model {
                if let Some(url) = peer_http_url(peer) {
                    return Some(url);
                }
            }
        }
    }
    None
}

/// Short-lived per-model TTL for the `all_shards_available` cache. Kept tiny
/// to stay consistent with shard announcement propagation delay.
const SHARD_AVAIL_CACHE_TTL_MS: u64 = 100;

/// Check if all layers for a model are covered across the network (for distributed inference).
/// This does NOT require any single node to have all shards — it only requires that every
/// shard has at least one holder somewhere in the network so the pipeline scheduler can
/// assemble a complete pipeline across multiple nodes.
pub fn all_shards_available(state: &AppState, model_name: &str) -> bool {
    // Short-lived per-model cache to avoid repeated ModelId/ShardId allocations
    use std::sync::LazyLock;
    static CACHE: LazyLock<dashmap::DashMap<String, (std::time::Instant, bool)>> =
        LazyLock::new(dashmap::DashMap::new);
    let ttl = std::time::Duration::from_millis(SHARD_AVAIL_CACHE_TTL_MS);
    if let Some(entry) = CACHE.get(model_name) {
        if entry.0.elapsed() < ttl {
            return entry.1;
        }
    }

    let result = all_shards_available_inner(state, model_name);
    // Evict stale entries instead of clearing entire cache (prevents thundering herd)
    const SHARD_AVAIL_CACHE_MAX: usize = 1_000;
    if CACHE.len() > SHARD_AVAIL_CACHE_MAX {
        CACHE.retain(|_, (ts, _)| ts.elapsed() < ttl);
    }
    CACHE.insert(model_name.to_string(), (std::time::Instant::now(), result));
    result
}

fn all_shards_available_inner(state: &AppState, model_name: &str) -> bool {
    let model_id = ModelId(model_name.to_string());

    let manifest = match state.shared_state.model_registry.get_manifest(&model_id) {
        Some(m) => m,
        None => {
            tracing::debug!(model = %model_name, "all_shards_available: no manifest");
            return false;
        }
    };

    // Need a valid layer count for the scheduler to work
    if manifest.num_layers == 0 {
        tracing::debug!(model = %model_name, "all_shards_available: num_layers=0");
        return false;
    }

    let total = manifest.shards.len();
    let mut covered = 0;
    for shard_info in &manifest.shards {
        let shard_id = crate::types::ShardId {
            model_id: model_id.clone(),
            index: shard_info.index,
        };
        let holders = state.shared_state.model_registry.shard_holders(&shard_id);
        if holders.is_empty() {
            tracing::debug!(
                model = %model_name,
                shard = shard_info.index,
                "all_shards_available: no node in network holds this shard"
            );
            return false;
        }
        covered += 1;
    }

    tracing::debug!(
        model = %model_name,
        shards = total,
        covered,
        num_layers = manifest.num_layers,
        "all_shards_available: all layers covered across network"
    );
    true
}

/// Resolve a model name for inference: handles "auto" alias and display-name → registry-ID mapping.
///
/// 1. If a local model is loaded and the request matches (by "auto", registry ID, or display name),
///    returns the resolved registry ID.
/// 2. For "auto" with no loaded model, falls back to the first model in the registry.
/// 3. Otherwise returns the original model name unchanged.
pub async fn resolve_model_for_inference(state: &AppState, model: &str) -> String {
    let info = state.shared_state.loaded_model_info.read().await;
    if let Some(i) = info.as_ref() {
        let resolved = resolve_loaded_model_registry_id(state, &i.name);
        if model == "auto" || model == resolved || model == i.name {
            return resolved;
        }
    }
    if model == "auto" {
        if let Some(m) = state
            .shared_state
            .model_registry
            .models()
            .into_iter()
            .next()
        {
            return m.id.0.clone();
        }
    }
    model.to_string()
}

/// Resolve a loaded model's display name to its registry ID.
///
/// Looks up the model in the registry by slug, then by display name.
/// Returns the registry ID if found, otherwise returns the slugified name.
pub fn resolve_loaded_model_registry_id(state: &AppState, model_display_name: &str) -> String {
    let slug = crate::types::slugify_model_name(model_display_name);
    state
        .shared_state
        .model_registry
        .get_manifest(&crate::types::ModelId(slug.clone()))
        .map(|m| m.id.0.clone())
        .or_else(|| {
            state
                .shared_state
                .model_registry
                .models()
                .into_iter()
                .find(|m| m.name == model_display_name)
                .map(|m| m.id.0.clone())
        })
        .unwrap_or(slug)
}

/// Check if a requested model matches the currently loaded model.
///
/// Returns true if the request matches by slug, display name, or registry ID.
pub fn model_matches_loaded(state: &AppState, loaded_name: &str, requested: &str) -> bool {
    let slug = crate::types::slugify_model_name(loaded_name);
    requested == slug
        || requested == loaded_name
        || state
            .shared_state
            .model_registry
            .get_manifest(&crate::types::ModelId(requested.to_string()))
            .is_some()
}

/// Resolve the model name to look up for inference (returns display name if available).
///
/// Checks loaded_model_info cache first, verifying it matches the request.
/// Falls back to manifest registry. Used by openai and anthropic handlers.
pub async fn resolve_model_name(state: &AppState, requested_model: &str) -> Option<String> {
    let info = state.shared_state.loaded_model_info.read().await;
    let cached_name = info.as_ref().map(|i| i.name.clone());
    let matches_request = info.as_ref().is_some_and(|i| {
        let slug = crate::types::slugify_model_name(&i.name);
        slug == requested_model || i.name == requested_model
    });
    drop(info);
    if matches_request {
        cached_name
    } else {
        state
            .shared_state
            .model_registry
            .get_manifest(&crate::types::ModelId(requested_model.to_string()))
            .map(|m| m.name.clone())
    }
}

/// Metadata extracted from a split model entry for prompt building.
pub struct SplitModelMeta {
    pub chat_template: Option<String>,
    pub bos_token: String,
    pub eos_token_str: String,
    pub layer_range: (u32, u32),
}

/// Look up split model metadata by model ID. Used by openai and anthropic handlers.
pub fn get_split_model_meta(
    state: &AppState,
    model_id: &crate::types::ModelId,
) -> Option<SplitModelMeta> {
    state
        .shared_state
        .split_models
        .iter()
        .find(|e| e.key().0 == *model_id)
        .map(|entry| {
            let e = entry.value();
            SplitModelMeta {
                chat_template: e.cached_chat_template.clone(),
                bos_token: e.bos_token.clone(),
                eos_token_str: e.eos_token_str.clone(),
                layer_range: (e.layer_start as u32, e.layer_end as u32),
            }
        })
}

/// Spawn a split-model generation task and return the token receiver.
///
/// Resolves model metadata, builds the prompt, and spawns the worker subprocess.
/// Returns None if the model is not loaded as a split model.
pub fn spawn_split_stream(
    state: &AppState,
    model_id: &crate::types::ModelId,
    messages: &[crate::types::ChatMessage],
    params: crate::types::SamplingParams,
    request_id: &str,
) -> Option<tokio::sync::mpsc::Receiver<crate::inference::router::StreamingTokenEvent>> {
    let meta = get_split_model_meta(state, model_id)?;
    let prompt = crate::inference::chat_template::build_prompt(
        messages,
        meta.chat_template.as_deref(),
        &meta.bos_token,
        &meta.eos_token_str,
    );
    let rid = uuid::Uuid::parse_str(request_id).unwrap_or_else(|_| uuid::Uuid::new_v4());
    let (token_tx, token_rx) =
        tokio::sync::mpsc::channel::<crate::inference::router::StreamingTokenEvent>(64);
    let pool = state.shared_state.model_process_pool.clone();
    let model_id = model_id.clone();
    let layer_range = meta.layer_range;
    tokio::spawn(async move {
        let _ = pool
            .generate(
                &model_id,
                layer_range,
                prompt,
                params,
                rid,
                None,
                Some(token_tx),
            )
            .await;
    });
    Some(token_rx)
}

/// Submit a streaming inference request to the router.
///
/// Creates the InferenceRequest and sends StreamSubmit. Returns receivers for
/// the final result and streaming tokens. Used by both openai and anthropic handlers.
pub async fn submit_stream_to_router(
    router_tx: &tokio::sync::mpsc::Sender<RouterCommand>,
    model_id: ModelId,
    messages: Vec<ChatMessage>,
    sampling_params: SamplingParams,
    session_id: Option<String>,
    lora_adapter: Option<String>,
) -> Result<
    (
        tokio::sync::oneshot::Receiver<
            Result<crate::inference::router::InferenceOutput, crate::error::SwarmError>,
        >,
        tokio::sync::mpsc::Receiver<StreamingTokenEvent>,
    ),
    ApiError,
> {
    let (result_tx, result_rx) = tokio::sync::oneshot::channel();
    let (token_tx, token_rx) = tokio::sync::mpsc::channel::<StreamingTokenEvent>(64);

    let inference_req = InferenceRequest::local(
        model_id,
        messages,
        sampling_params,
        true,
        session_id,
        lora_adapter,
    );

    router_tx
        .send(RouterCommand::StreamSubmit {
            request: inference_req,
            result_tx,
            token_tx,
        })
        .await
        .map_err(|_| {
            ApiError(crate::error::SwarmError::ServiceUnavailable(
                "Router unavailable".into(),
            ))
        })?;

    Ok((result_rx, token_rx))
}

/// Run non-streaming inference on a local split model.
///
/// Shared core for both OpenAI and Anthropic split_non_stream handlers.
/// Resolves model metadata, builds the prompt, and runs generation via subprocess.
pub async fn run_split_generate(
    state: &AppState,
    model_id: &crate::types::ModelId,
    messages: &[ChatMessage],
    params: SamplingParams,
    request_id: &str,
) -> Result<crate::inference::router::InferenceOutput, ApiError> {
    let meta = get_split_model_meta(state, model_id)
        .ok_or(ApiError(crate::error::SwarmError::NoModelLoaded))?;

    let prompt = chat_template::build_prompt(
        messages,
        meta.chat_template.as_deref(),
        &meta.bos_token,
        &meta.eos_token_str,
    );

    tracing::debug!(
        request_id = %request_id,
        prompt_len = prompt.len(),
        "DIAG: non-stream built prompt (subprocess)"
    );

    let rid = uuid::Uuid::parse_str(request_id).unwrap_or_else(|_| uuid::Uuid::new_v4());
    state
        .shared_state
        .model_process_pool
        .generate(model_id, meta.layer_range, prompt, params, rid, None, None)
        .await
        .map_err(ApiError)
}

/// Decode token IDs to text using the split model's tokenizer.
///
/// Uses BPE tokenizer byte decoding for proper UTF-8 handling (GPT-2 byte
/// encoding, SentencePiece byte fallbacks, etc).
fn peer_http_url(peer: &crate::types::PeerInfo) -> Option<String> {
    // Prefer UDP port (QUIC port == HTTP API port per convention),
    // fall back to TCP port - 10 (P2P TCP = HTTP + 10).
    let mut best_ip = None;
    let mut best_port = None;
    let mut have_udp = false;

    for addr in &peer.addresses {
        let parts: Vec<&str> = addr.split('/').collect();
        let mut ip = None;
        let mut udp_port = None;
        let mut tcp_port = None;
        for i in 0..parts.len() {
            if parts[i] == "ip4" && i + 1 < parts.len() {
                ip = Some(parts[i + 1]);
            }
            if parts[i] == "udp" && i + 1 < parts.len() {
                udp_port = Some(parts[i + 1]);
            }
            if parts[i] == "tcp" && i + 1 < parts.len() {
                tcp_port = Some(parts[i + 1]);
            }
        }
        if let Some(ip_str) = ip {
            if let Ok(parsed) = ip_str.parse::<std::net::Ipv4Addr>() {
                // Skip loopback, unspecified, and private IP ranges to prevent
                // SSRF via gossip-controlled peer addresses
                if parsed.is_loopback()
                    || parsed.is_unspecified()
                    || parsed.is_private()
                    || parsed.is_link_local()
                {
                    continue;
                }
            }
            // UDP port == HTTP API port (preferred)
            if let Some(port_str) = udp_port {
                if !have_udp {
                    best_ip = Some(ip_str.to_string());
                    best_port = Some(port_str.to_string());
                    have_udp = true;
                }
            }
            // TCP port = HTTP + 10, so HTTP = TCP - 10
            if let Some(port_str) = tcp_port {
                if !have_udp {
                    if let Ok(p) = port_str.parse::<u16>() {
                        best_ip = Some(ip_str.to_string());
                        best_port = Some(p.saturating_sub(10).to_string());
                    }
                }
            }
        }
    }
    match (best_ip, best_port) {
        (Some(ip), Some(port)) => Some(format!("http://{}:{}", ip, port)),
        _ => None,
    }
}

/// Forward a chat completion request to a peer's HTTP API.
/// Lazily-initialized shared reqwest client for peer forwarding.
/// Avoids creating a new TLS + connection pool on every request.
static PEER_CLIENT: std::sync::LazyLock<reqwest::Client> = std::sync::LazyLock::new(|| {
    reqwest::Client::builder()
        .connect_timeout(std::time::Duration::from_secs(10))
        .timeout(std::time::Duration::from_secs(
            INFERENCE_FORWARD_TIMEOUT_SECS,
        ))
        .build()
        .unwrap_or_else(|_| reqwest::Client::new())
});

fn get_peer_client() -> &'static reqwest::Client {
    &PEER_CLIENT
}

async fn forward_to_peer(
    peer_url: &str,
    req: &ChatCompletionRequest,
    stream: bool,
) -> Result<axum::response::Response, ApiError> {
    let client = get_peer_client();
    let url = format!("{}/v1/chat/completions", peer_url);

    let peer_resp = client
        .post(&url)
        .header("x-swarm-forwarded", "true")
        .json(req)
        .send()
        .await
        .map_err(|e| {
            tracing::warn!(error = %e, url = %url, "Failed to forward to peer");
            ApiError(crate::error::SwarmError::Network(format!(
                "Peer forwarding failed: {e}"
            )))
        })?;

    if !peer_resp.status().is_success() {
        let status = peer_resp.status();
        let raw_body = peer_resp.text().await.unwrap_or_default();
        let body = super::scrub_truncate_error(&raw_body);
        tracing::warn!(status = %status, body = %body, "Peer returned error");
        return Err(ApiError(crate::error::SwarmError::ProviderError {
            status: status.as_u16(),
            body,
        }));
    }

    let response = crate::api::providers::build_passthrough_response(peer_resp, stream).await?;
    Ok(response.into_response())
}

/// Dispatch to `router_inference` or `router_inference_stream` based on `req.stream`.
async fn dispatch_inference(
    router_tx: tokio::sync::mpsc::Sender<RouterCommand>,
    state: &AppState,
    req: &ChatCompletionRequest,
    messages: Vec<ChatMessage>,
    request_id: String,
    created: i64,
) -> Result<axum::response::Response, ApiError> {
    if req.stream {
        router_inference_stream(router_tx, state, req, messages, request_id, created).await
    } else {
        router_inference(router_tx, req, messages, request_id, created).await
    }
}

/// Route inference through the InferenceRouter (non-streaming).
async fn router_inference(
    router_tx: tokio::sync::mpsc::Sender<RouterCommand>,
    req: &ChatCompletionRequest,
    messages: Vec<ChatMessage>,
    request_id: String,
    created: i64,
) -> Result<axum::response::Response, ApiError> {
    let inference_req = InferenceRequest::local(
        ModelId(req.model.clone()),
        messages,
        req.to_sampling_params(),
        false,
        req.session_id.clone(),
        req.lora_adapter.clone(),
    );

    let output = super::submit_to_router(&router_tx, inference_req).await?;

    let response = ChatCompletionResponse {
        id: request_id,
        object: "chat.completion",
        created,
        model: req.model.clone(),
        choices: vec![ChatChoice {
            index: 0,
            message: ChatMessageResponse {
                role: "assistant".into(),
                content: Some(output.content),
                tool_calls: None,
            },
            finish_reason: output.finish_reason,
            logprobs: if output.token_logprobs.is_empty() {
                None
            } else {
                Some(ChoiceLogProbs {
                    content: output
                        .token_logprobs
                        .iter()
                        .map(|entry| TokenLogProb {
                            token: entry.token.clone(),
                            logprob: entry.logprob,
                            bytes: None,
                            top_logprobs: entry
                                .top_logprobs
                                .iter()
                                .map(|(t, lp)| TopLogProb {
                                    token: t.clone(),
                                    logprob: *lp,
                                    bytes: None,
                                })
                                .collect(),
                        })
                        .collect(),
                })
            },
        }],
        usage: Usage {
            prompt_tokens: output.prompt_tokens,
            completion_tokens: output.completion_tokens,
            total_tokens: output.prompt_tokens + output.completion_tokens,
            cache_creation_input_tokens: None,
            cache_read_input_tokens: None,
        },
        session_id: output.session_id,
    };

    Ok(Json(response).into_response())
}

/// Route streaming inference through the InferenceRouter.
///
/// Submits the request via `StreamSubmit` so the pipeline executor sends decoded
/// tokens incrementally. Each token is forwarded as an SSE chunk, providing true
/// token-by-token streaming for distributed inference.
async fn router_inference_stream(
    router_tx: tokio::sync::mpsc::Sender<RouterCommand>,
    _state: &AppState,
    req: &ChatCompletionRequest,
    messages: Vec<ChatMessage>,
    request_id: String,
    created: i64,
) -> Result<axum::response::Response, ApiError> {
    let (result_rx, mut token_rx) = submit_stream_to_router(
        &router_tx,
        ModelId(req.model.clone()),
        messages,
        req.to_sampling_params(),
        req.session_id.clone(),
        req.lora_adapter.clone(),
    )
    .await?;

    let model_name = req.model.clone();
    let rid = request_id.clone();
    let stream_session_id = req.session_id.clone();

    // Bridge the streaming token channel into SSE events
    let (sse_tx, sse_rx) = tokio::sync::mpsc::channel::<StreamEvent>(64);

    tokio::spawn(async move {
        let stream_start = std::time::Instant::now();
        let mut token_count: u64 = 0;

        // Send initial role delta
        if !send_role_preamble(&sse_tx).await {
            tracing::warn!(
                "DIAG: SSE role delta send failed — client disconnected before stream started"
            );
            return;
        }

        // Read tokens from the pipeline as they arrive
        let mut got_finish = false;
        let mut client_disconnected = false;
        while let Some(event) = token_rx.recv().await {
            if let Some(ref reason) = event.finish_reason {
                got_finish = true;
                if !event.text.is_empty() {
                    token_count += 1;
                    if sse_tx
                        .send(StreamEvent::Delta {
                            content: Some(event.text),
                            role: None,
                            finish_reason: None,
                        })
                        .await
                        .is_err()
                    {
                        tracing::warn!(
                            token_count,
                            "DIAG: SSE final text delta send failed — client disconnected"
                        );
                    }
                }
                if sse_tx
                    .send(StreamEvent::Delta {
                        content: None,
                        role: None,
                        finish_reason: Some(reason.clone()),
                    })
                    .await
                    .is_err()
                {
                    tracing::debug!(token_count, finish_reason = %reason, "DIAG: SSE finish delta send failed — client disconnected");
                }
                break;
            }
            if !event.text.is_empty() {
                token_count += 1;
                if sse_tx
                    .send(StreamEvent::Delta {
                        content: Some(event.text),
                        role: None,
                        finish_reason: None,
                    })
                    .await
                    .is_err()
                {
                    tracing::warn!(
                        token_count,
                        elapsed_ms = stream_start.elapsed().as_millis() as u64,
                        "DIAG: SSE client disconnected mid-stream — cancelling pipeline"
                    );
                    client_disconnected = true;
                    break;
                }
            }
        }

        // Client disconnected: drop token_rx to signal pipeline to stop generating,
        // and skip the result_rx fallback to avoid blocking on a now-useless pipeline.
        if client_disconnected {
            drop(token_rx);
            tracing::info!(
                token_count,
                elapsed_ms = stream_start.elapsed().as_millis() as u64,
                "SSE pipeline cancelled due to client disconnect"
            );
            // Send Done in case sse_rx is still draining
            let _ = sse_tx.send(StreamEvent::Done).await;
            return;
        }

        // Fallback: if pipeline finished without sending streaming events
        // (e.g., local-only path or error), read the final result.
        if !got_finish {
            tracing::debug!(
                token_count,
                "DIAG: SSE stream no finish event from pipeline, reading result_rx fallback"
            );
            match result_rx.await {
                Ok(Ok(output)) => {
                    if !output.content.is_empty()
                        && sse_tx
                            .send(StreamEvent::Delta {
                                content: Some(output.content),
                                role: None,
                                finish_reason: None,
                            })
                            .await
                            .is_err()
                    {
                        tracing::warn!(
                            "DIAG: SSE fallback content send failed — client disconnected"
                        );
                    }
                    if sse_tx
                        .send(StreamEvent::Delta {
                            content: None,
                            role: None,
                            finish_reason: Some(output.finish_reason.clone()),
                        })
                        .await
                        .is_err()
                    {
                        tracing::debug!(finish_reason = %output.finish_reason, "DIAG: SSE fallback finish send failed");
                    }
                }
                Ok(Err(e)) => {
                    tracing::debug!(error = %e, "DIAG: SSE fallback got pipeline error");
                    if sse_tx
                        .send(StreamEvent::Error {
                            message: format!("{e}"),
                        })
                        .await
                        .is_err()
                    {
                        tracing::debug!("DIAG: SSE error event send failed — client disconnected");
                    }
                }
                Err(_) => {
                    tracing::debug!("DIAG: SSE result_rx channel dropped — pipeline task died without sending result");
                    if sse_tx
                        .send(StreamEvent::Delta {
                            content: None,
                            role: None,
                            finish_reason: Some("stop".into()),
                        })
                        .await
                        .is_err()
                    {
                        tracing::debug!("DIAG: SSE channel-drop finish send also failed");
                    }
                }
            }
        }
        if sse_tx.send(StreamEvent::Done).await.is_err() {
            tracing::debug!("DIAG: SSE Done send failed — client already disconnected");
        }
        let elapsed = stream_start.elapsed();
        tracing::info!(
            elapsed_ms = elapsed.as_millis() as u64,
            token_count,
            "DIAG: SSE distributed stream completed"
        );
    });

    Ok(stream_events_to_sse(sse_rx, rid, created, model_name, stream_session_id).into_response())
}

/// Direct split-model generation (non-streaming).
///
/// Bypasses the distributed pipeline executor and generates directly from
/// the locally loaded SplitModel. Much faster for single-node inference
/// because it avoids per-token pipeline coordination overhead.
/// Builds the prompt from the model's own chat template to avoid template mismatch.
async fn split_non_stream_response(
    state: AppState,
    request_id: String,
    created: i64,
    model_name: String,
    messages: Vec<ChatMessage>,
    params: SamplingParams,
    model_id: crate::types::ModelId,
) -> Result<axum::response::Response, ApiError> {
    let output =
        run_split_generate(&state, &model_id, &messages, params.clone(), &request_id).await?;

    let response = ChatCompletionResponse {
        id: request_id,
        object: "chat.completion",
        created,
        model: model_name,
        choices: vec![ChatChoice {
            index: 0,
            message: ChatMessageResponse {
                role: "assistant".into(),
                content: Some(output.content),
                tool_calls: None,
            },
            finish_reason: output.finish_reason.clone(),
            logprobs: None,
        }],
        usage: Usage {
            prompt_tokens: output.prompt_tokens,
            completion_tokens: output.completion_tokens,
            total_tokens: output.prompt_tokens + output.completion_tokens,
            cache_creation_input_tokens: None,
            cache_read_input_tokens: None,
        },
        session_id: None,
    };

    Ok(Json(response).into_response())
}

/// Direct split-model streaming generation.
///
/// Same fast path as split_non_stream_response but streams tokens via SSE.
/// Builds the prompt from the model's own chat template to avoid template mismatch.
async fn split_stream_response(
    state: AppState,
    request_id: String,
    created: i64,
    model_name: String,
    messages: Vec<ChatMessage>,
    params: SamplingParams,
    model_id: crate::types::ModelId,
) -> Sse<impl Stream<Item = Result<Event, Infallible>>> {
    let (tx, rx) = tokio::sync::mpsc::channel::<StreamEvent>(64);
    let request_id_inner = request_id.clone();

    tokio::spawn(async move {
        let request_id = request_id_inner;
        // Send initial role delta
        let stream_start = std::time::Instant::now();
        let mut token_count: u64 = 0;

        if !send_role_preamble(&tx).await {
            tracing::debug!("DIAG: split stream role delta send failed — client disconnected");
            return;
        }

        // Spawn split-model generation and get token receiver
        let mut token_rx =
            match spawn_split_stream(&state, &model_id, &messages, params, &request_id) {
                Some(rx) => rx,
                None => {
                    tracing::debug!(model_id = %model_id, "DIAG: split stream model not found");
                    let _ = tx.send(StreamEvent::Done).await;
                    return;
                }
            };

        // Forward streaming tokens from the worker to SSE events
        let mut finish = "length".to_string();
        while let Some(event) = token_rx.recv().await {
            if let Some(fr) = &event.finish_reason {
                finish = fr.clone();
                break;
            }
            token_count += 1;
            if tx
                .send(StreamEvent::Delta {
                    content: Some(event.text),
                    role: None,
                    finish_reason: None,
                })
                .await
                .is_err()
            {
                tracing::warn!(
                    token_count,
                    elapsed_ms = stream_start.elapsed().as_millis() as u64,
                    "DIAG: split stream client disconnected mid-decode"
                );
                return;
            }
        }

        tracing::info!(
            model_id = %model_id,
            token_count,
            finish = %finish,
            "DIAG: split stream decode loop complete (subprocess)"
        );

        // Send finish
        if tx
            .send(StreamEvent::Delta {
                content: None,
                role: None,
                finish_reason: Some(finish),
            })
            .await
            .is_err()
        {
            tracing::debug!(token_count, "DIAG: split stream finish delta send failed");
        }
        if tx.send(StreamEvent::Done).await.is_err() {
            tracing::debug!("DIAG: split stream Done send failed — client disconnected");
        }
        let elapsed = stream_start.elapsed();
        tracing::info!(
            elapsed_ms = elapsed.as_millis() as u64,
            token_count,
            "DIAG: split stream completed"
        );
    });

    stream_events_to_sse(rx, request_id, created, model_name, None)
}

async fn stream_response(
    state: AppState,
    request_id: String,
    created: i64,
    model_name: String,
    prompt: String,
    params: SamplingParams,
) -> Sse<impl Stream<Item = Result<Event, Infallible>>> {
    let (tx, rx) = tokio::sync::mpsc::channel::<StreamEvent>(64);

    // Spawn generation in background
    tokio::spawn(async move {
        let stream_start = std::time::Instant::now();
        let mut token_count: u64 = 0;

        // Send initial role delta
        if !send_role_preamble(&tx).await {
            tracing::debug!("DIAG: local stream role delta send failed — client disconnected");
            return;
        }

        let mut executor = state.executor.lock().await;
        let result = executor.generate_stream(&prompt, &params, |token| {
            token_count += 1;
            let send_result = tx.try_send(StreamEvent::Delta {
                content: Some(token.to_string()),
                role: None,
                finish_reason: None,
            });
            if send_result.is_err() {
                tracing::warn!(
                    token_count,
                    "DIAG: local stream token send failed — channel full or client disconnected"
                );
            }
            send_result.is_ok()
        });

        // Send finish reason
        let finish = match result {
            Ok(r) => r.finish_reason.as_str().to_string(),
            Err(ref e) => {
                tracing::error!(error = %e, "DIAG: local stream generate_stream error");
                "error".to_string()
            }
        };
        if tx
            .send(StreamEvent::Delta {
                content: None,
                role: None,
                finish_reason: Some(finish.clone()),
            })
            .await
            .is_err()
        {
            tracing::debug!(token_count, finish_reason = %finish, "DIAG: local stream finish send failed");
        }
        if tx.send(StreamEvent::Done).await.is_err() {
            tracing::debug!("DIAG: local stream Done send failed — client disconnected");
        }
        let elapsed = stream_start.elapsed();
        tracing::info!(
            elapsed_ms = elapsed.as_millis() as u64,
            token_count,
            "DIAG: local stream completed"
        );
    });

    stream_events_to_sse(rx, request_id, created, model_name, None)
}

/// Convert a StreamEvent receiver into an SSE stream of OpenAI-format chat completion chunks.
fn stream_events_to_sse(
    rx: tokio::sync::mpsc::Receiver<StreamEvent>,
    request_id: String,
    created: i64,
    model_name: String,
    session_id: Option<String>,
) -> Sse<impl futures::Stream<Item = Result<Event, Infallible>>> {
    let mut json_buf = Vec::with_capacity(512);
    let stream = tokio_stream::wrappers::ReceiverStream::new(rx).map(move |event| match event {
        StreamEvent::Delta {
            content,
            role,
            finish_reason,
        } => {
            let sid = if finish_reason.is_some() {
                session_id.clone()
            } else {
                None
            };
            let chunk = ChatCompletionChunk {
                id: request_id.clone(),
                object: "chat.completion.chunk",
                created,
                model: model_name.clone(),
                choices: vec![ChunkChoice {
                    index: 0,
                    delta: Delta {
                        role,
                        content,
                        tool_calls: None,
                    },
                    finish_reason,
                    logprobs: None,
                }],
                session_id: sid,
            };
            json_buf.clear();
            let json = if serde_json::to_writer(&mut json_buf, &chunk).is_ok() {
                String::from_utf8(json_buf.clone()).unwrap_or_default()
            } else {
                String::new()
            };
            Ok::<_, Infallible>(Event::default().data(json))
        }
        StreamEvent::Error { message } => {
            let error_json = serde_json::json!({
                "error": {
                    "message": message,
                    "type": "server_error"
                }
            });
            Ok(Event::default().data(serde_json::to_string(&error_json).unwrap_or_default()))
        }
        StreamEvent::Done => Ok(Event::default().data("[DONE]")),
    });
    Sse::new(stream).keep_alive(
        KeepAlive::new().interval(std::time::Duration::from_secs(SSE_KEEPALIVE_INTERVAL_SECS)),
    )
}

enum StreamEvent {
    Delta {
        content: Option<String>,
        role: Option<String>,
        finish_reason: Option<String>,
    },
    Error {
        message: String,
    },
    Done,
}

/// Send the initial `role: "assistant"` delta that opens the streaming response.
/// Returns `false` if the client has already disconnected.
async fn send_role_preamble(tx: &tokio::sync::mpsc::Sender<StreamEvent>) -> bool {
    tx.send(StreamEvent::Delta {
        content: None,
        role: Some("assistant".into()),
        finish_reason: None,
    })
    .await
    .is_ok()
}

/// GET /v1/models
///
/// Lists models usable for inference. A model is usable when all its layers
/// are covered by at least one node in the network — no single node needs
/// the full shard set. Models still propagating across the network (some
/// layers uncovered) are excluded here but visible in the admin dashboard.
pub async fn list_models(State(state): State<AppState>) -> Json<ModelListResponse> {
    let mut data = vec![];
    let mut seen = std::collections::HashSet::new();

    // Use cached model info (lock-free, no executor contention)
    if let Some(info) = state.shared_state.loaded_model_info.read().await.as_ref() {
        seen.insert(info.name.clone());
        let slug = crate::types::slugify_model_name(&info.name);
        seen.insert(slug.clone());

        // Find the registry manifest for this model so we can use its canonical ID
        // and mark it as seen (prevents duplicates in section 2).
        let manifest = state
            .shared_state
            .model_registry
            .resolve_manifest_by_name(&info.name);

        let model_id = if let Some(ref m) = manifest {
            seen.insert(m.id.0.clone());
            m.id.0.clone()
        } else {
            slug
        };

        data.push(ModelInfo {
            id: model_id,
            object: "model",
            created: chrono::Utc::now().timestamp(),
            owned_by: "local".into(),
        });
    }

    // Include models from the registry if all layers are covered network-wide
    for manifest in state.shared_state.model_registry.models() {
        let id = manifest.id.0.clone();
        if seen.contains(&id) {
            continue;
        }
        if all_shards_available(&state, &id) {
            seen.insert(id.clone());
            data.push(ModelInfo {
                id,
                object: "model",
                created: manifest.publish_date.timestamp(),
                owned_by: "network".into(),
            });
        }
    }

    Json(ModelListResponse {
        object: "list",
        data,
    })
}

// ---- Embeddings ----

#[derive(Debug, Deserialize)]
pub struct EmbeddingRequest {
    pub model: String,
    pub input: EmbeddingInput,
    #[serde(default = "default_encoding_format")]
    pub encoding_format: String,
}

#[derive(Debug, Deserialize)]
#[serde(untagged)]
pub enum EmbeddingInput {
    Single(String),
    Batch(Vec<String>),
}

fn default_encoding_format() -> String {
    "float".into()
}

/// POST /v1/embeddings — OpenAI-compatible embeddings endpoint.
///
/// Not available with subprocess inference (Phase 17) — models run in isolated
/// worker processes without in-process tensor access. Use a dedicated embedding
/// model or cloud provider instead.
pub async fn embeddings(
    State(_state): State<AppState>,
    crate::api::server::JsonBody(_req): crate::api::server::JsonBody<EmbeddingRequest>,
) -> Result<Json<serde_json::Value>, ApiError> {
    Err(ApiError(crate::error::SwarmError::ServiceUnavailable(
        "Embeddings API not available with subprocess inference. Use a dedicated embedding model or provider.".into(),
    )))
}

/// GET /v1/status — SwarmLLM extension endpoint
pub async fn status(State(state): State<AppState>) -> Json<serde_json::Value> {
    let info = state.shared_state.loaded_model_info.read().await;
    let local_model = info.is_some();
    let model_name = info.as_ref().map(|i| i.name.clone()).unwrap_or_default();
    drop(info);

    // Count network-available models from peers
    let mut network_models = Vec::new();
    for entry in state.shared_state.peer_registry.iter() {
        if let Some(ref cap) = entry.value().capability {
            for shard in &cap.hosted_shards {
                network_models.push(shard.model_id.0.clone());
            }
        }
    }
    network_models.sort();
    network_models.dedup();

    Json(serde_json::json!({
        "status": "ok",
        "version": env!("CARGO_PKG_VERSION"),
        "model_loaded": local_model,
        "model_name": model_name,
        "network_models": network_models,
        "peers": state.shared_state.peer_registry.len(),
    }))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn tool_call_request_deserializes() {
        let json = r#"{
            "model": "test",
            "messages": [{"role": "user", "content": "What's the weather?"}],
            "tools": [{
                "type": "function",
                "function": {
                    "name": "get_weather",
                    "description": "Get current weather",
                    "parameters": {"type": "object", "properties": {"location": {"type": "string"}}}
                }
            }],
            "tool_choice": "auto"
        }"#;
        let req: ChatCompletionRequest = serde_json::from_str(json).unwrap();
        assert!(req.tools.is_some());
        let tools = req.tools.unwrap();
        assert_eq!(tools.len(), 1);
        assert_eq!(tools[0].function.name, "get_weather");
        assert_eq!(req.tool_choice, Some(serde_json::json!("auto")));
    }

    #[test]
    fn tool_role_message_deserializes() {
        let json = r#"{
            "role": "tool",
            "content": "{\"temperature\": 72}",
            "tool_call_id": "call_abc123"
        }"#;
        let msg: ApiChatMessage = serde_json::from_str(json).unwrap();
        assert!(matches!(msg.role, crate::types::Role::Tool));
        assert_eq!(msg.tool_call_id, Some("call_abc123".into()));
    }

    #[test]
    fn assistant_tool_calls_message_deserializes() {
        let json = r#"{
            "role": "assistant",
            "content": null,
            "tool_calls": [{
                "id": "call_abc123",
                "type": "function",
                "function": {"name": "get_weather", "arguments": "{\"location\":\"NYC\"}"}
            }]
        }"#;
        let msg: ApiChatMessage = serde_json::from_str(json).unwrap();
        let tc = msg.tool_calls.unwrap();
        assert_eq!(tc.len(), 1);
        assert_eq!(tc[0].id, "call_abc123");
        assert_eq!(tc[0].function.name, "get_weather");
    }

    #[test]
    fn logprobs_request_fields() {
        let json = r#"{
            "model": "test",
            "messages": [{"role": "user", "content": "hi"}],
            "logprobs": true,
            "top_logprobs": 5
        }"#;
        let req: ChatCompletionRequest = serde_json::from_str(json).unwrap();
        assert!(req.logprobs);
        assert_eq!(req.top_logprobs, Some(5));
        let params = req.to_sampling_params();
        assert!(params.logprobs);
        assert_eq!(params.top_logprobs, 5);
    }

    #[test]
    fn logprobs_response_serializes() {
        let choice = ChatChoice {
            index: 0,
            message: ChatMessageResponse {
                role: "assistant".into(),
                content: Some("hello".into()),
                tool_calls: None,
            },
            finish_reason: "stop".into(),
            logprobs: Some(ChoiceLogProbs {
                content: vec![TokenLogProb {
                    token: "hello".into(),
                    logprob: -0.5,
                    bytes: None,
                    top_logprobs: vec![
                        TopLogProb {
                            token: "hello".into(),
                            logprob: -0.5,
                            bytes: None,
                        },
                        TopLogProb {
                            token: "hi".into(),
                            logprob: -1.2,
                            bytes: None,
                        },
                    ],
                }],
            }),
        };
        let json = serde_json::to_string(&choice).unwrap();
        assert!(json.contains("\"logprobs\""));
        assert!(json.contains("\"top_logprobs\""));
        assert!(json.contains("-0.5"));
    }

    #[test]
    fn tool_calls_response_serializes() {
        let choice = ChatChoice {
            index: 0,
            message: ChatMessageResponse {
                role: "assistant".into(),
                content: None,
                tool_calls: Some(vec![ToolCall {
                    id: "call_123".into(),
                    tool_type: "function".into(),
                    function: FunctionCall {
                        name: "get_weather".into(),
                        arguments: r#"{"location":"NYC"}"#.into(),
                    },
                }]),
            },
            finish_reason: "tool_calls".into(),
            logprobs: None,
        };
        let json = serde_json::to_string(&choice).unwrap();
        assert!(json.contains("\"tool_calls\""));
        assert!(json.contains("\"call_123\""));
        assert!(json.contains("\"tool_calls\"")); // finish_reason
                                                  // content should be absent when None
        assert!(!json.contains("\"content\""));
    }

    #[test]
    fn request_without_tools_works() {
        let json = r#"{
            "model": "test",
            "messages": [{"role": "user", "content": "hi"}]
        }"#;
        let req: ChatCompletionRequest = serde_json::from_str(json).unwrap();
        assert!(req.tools.is_none());
        assert!(!req.logprobs);
        assert!(req.top_logprobs.is_none());
    }

    #[test]
    fn format_tool_system_prompt_output() {
        let tools = vec![ToolDefinition {
            tool_type: "function".into(),
            function: FunctionDefinition {
                name: "get_weather".into(),
                description: Some("Get weather info".into()),
                parameters: Some(serde_json::json!({"type": "object"})),
            },
        }];
        let prompt = format_tool_system_prompt(&tools);
        assert!(prompt.contains("get_weather"));
        assert!(prompt.contains("Get weather info"));
        assert!(prompt.contains("Parameters:"));
    }

    #[test]
    fn stream_delta_tool_calls_serializes() {
        let delta = Delta {
            role: Some("assistant".into()),
            content: None,
            tool_calls: Some(vec![StreamToolCall {
                index: 0,
                id: Some("call_1".into()),
                tool_type: Some("function".into()),
                function: Some(StreamFunctionCall {
                    name: Some("get_weather".into()),
                    arguments: Some("{".into()),
                }),
            }]),
        };
        let json = serde_json::to_string(&delta).unwrap();
        assert!(json.contains("\"tool_calls\""));
        assert!(json.contains("\"call_1\""));
    }

    #[test]
    fn response_format_json_object_deserializes() {
        let json = r#"{
            "model": "test",
            "messages": [{"role": "user", "content": "hi"}],
            "response_format": {"type": "json_object"}
        }"#;
        let req: ChatCompletionRequest = serde_json::from_str(json).unwrap();
        assert!(matches!(
            req.response_format,
            Some(ResponseFormat::JsonObject)
        ));
    }

    #[test]
    fn response_format_json_schema_deserializes() {
        let json = r#"{
            "model": "test",
            "messages": [{"role": "user", "content": "hi"}],
            "response_format": {
                "type": "json_schema",
                "json_schema": {
                    "name": "person",
                    "schema": {"type": "object", "properties": {"name": {"type": "string"}}},
                    "strict": true
                }
            }
        }"#;
        let req: ChatCompletionRequest = serde_json::from_str(json).unwrap();
        match req.response_format {
            Some(ResponseFormat::JsonSchema { ref json_schema }) => {
                assert_eq!(json_schema.name, "person");
                assert!(json_schema.strict);
            }
            _ => panic!("expected JsonSchema"),
        }
    }

    #[test]
    fn response_format_text_deserializes() {
        let json = r#"{
            "model": "test",
            "messages": [{"role": "user", "content": "hi"}],
            "response_format": {"type": "text"}
        }"#;
        let req: ChatCompletionRequest = serde_json::from_str(json).unwrap();
        assert!(matches!(req.response_format, Some(ResponseFormat::Text)));
    }

    #[test]
    fn response_format_absent_is_none() {
        let json = r#"{
            "model": "test",
            "messages": [{"role": "user", "content": "hi"}]
        }"#;
        let req: ChatCompletionRequest = serde_json::from_str(json).unwrap();
        assert!(req.response_format.is_none());
    }

    #[test]
    fn cache_control_request_deserializes() {
        let json = r#"{
            "model": "test",
            "messages": [{"role": "user", "content": "hi"}],
            "cache_control": {"type": "ephemeral", "prefix_messages": 2}
        }"#;
        let req: ChatCompletionRequest = serde_json::from_str(json).unwrap();
        let cc = req.cache_control.unwrap();
        assert_eq!(cc.r#type.as_deref(), Some("ephemeral"));
        assert_eq!(cc.prefix_messages, Some(2));
    }

    #[test]
    fn cache_control_persistent_type() {
        let json = r#"{
            "model": "test",
            "messages": [{"role": "user", "content": "hi"}],
            "cache_control": {"type": "persistent"}
        }"#;
        let req: ChatCompletionRequest = serde_json::from_str(json).unwrap();
        let cc = req.cache_control.unwrap();
        assert_eq!(cc.r#type.as_deref(), Some("persistent"));
        assert!(cc.prefix_messages.is_none());
    }

    #[test]
    fn cache_control_absent_is_none() {
        let json = r#"{
            "model": "test",
            "messages": [{"role": "user", "content": "hi"}]
        }"#;
        let req: ChatCompletionRequest = serde_json::from_str(json).unwrap();
        assert!(req.cache_control.is_none());
    }

    #[test]
    fn per_message_cache_control_deserializes() {
        let json = r#"{
            "role": "system",
            "content": "You are helpful",
            "cache_control": {"type": "ephemeral"}
        }"#;
        let msg: ApiChatMessage = serde_json::from_str(json).unwrap();
        let cc = msg.cache_control.unwrap();
        assert_eq!(cc.r#type.as_deref(), Some("ephemeral"));
    }

    #[test]
    fn usage_cache_stats_serialize_when_present() {
        let usage = Usage {
            prompt_tokens: 100,
            completion_tokens: 50,
            total_tokens: 150,
            cache_creation_input_tokens: Some(80),
            cache_read_input_tokens: Some(0),
        };
        let json = serde_json::to_string(&usage).unwrap();
        assert!(json.contains("\"cache_creation_input_tokens\":80"));
        assert!(json.contains("\"cache_read_input_tokens\":0"));
    }

    #[test]
    fn usage_cache_stats_omitted_when_none() {
        let usage = Usage {
            prompt_tokens: 100,
            completion_tokens: 50,
            total_tokens: 150,
            cache_creation_input_tokens: None,
            cache_read_input_tokens: None,
        };
        let json = serde_json::to_string(&usage).unwrap();
        assert!(!json.contains("cache_creation_input_tokens"));
        assert!(!json.contains("cache_read_input_tokens"));
    }

    #[test]
    fn json_schema_injects_system_prompt() {
        let json = r#"{
            "model": "test",
            "messages": [{"role": "user", "content": "hi"}],
            "response_format": {
                "type": "json_schema",
                "json_schema": {
                    "name": "result",
                    "schema": {"type": "object"}
                }
            }
        }"#;
        let req: ChatCompletionRequest = serde_json::from_str(json).unwrap();
        let msgs = req.to_internal_messages().unwrap();
        // Should have 2 messages: injected system + original user
        assert_eq!(msgs.len(), 2);
        assert!(matches!(msgs[0].role, crate::types::Role::System));
        assert!(msgs[0].content.contains("valid JSON"));
        assert!(msgs[0].content.contains("result"));
    }
}
